use cuatro_cuadras
Go
---6to Paso: Cargas iniciales(Población)

---Categoría
select*from Categoria
insert into Categoria (nombre,descripcion)
values('Restaurante','Lugar para comer')
insert into categoria (nombre,descripcion)
values('Tienda de videojuegos','Lugar para jugar y comprar videojuegos')
insert into categoria (nombre,descripcion)
values('Bar','Lugar para consumir alcohol')
insert into categoria (nombre,descripcion)
values('Centro Comercial','Espacio donde se albergan distintos locales comerciales')
insert into categoria (nombre,descripcion)
values('Boutique','Lugar para comprar ropa o telas')
insert into categoria (nombre,descripcion)
values('Club nocturno','Local público donde se escucha y baila música pregrabada ')
insert into categoria (nombre,descripcion)
values('Perfumeria','Lugares donde se mezclan y comercializan mezclas para producir perfumería')
insert into categoria (nombre,descripcion)
values('Zapateria','Local comercial donde se ofrecen zapatos de distintos tipos')
insert into categoria (nombre,descripcion)
values('Muebleria','Local comercial que distribuye muebles y piezas para decoración')
insert into categoria (nombre,descripcion)
values('Carniceria ','Local donde se comercializa carne de distinas reces y ganado')
insert into categoria (nombre,descripcion)
values('Museo','Lugar donde se observan colecciones de objetos diversos')
insert into categoria (nombre,descripcion)
values('Cine','Sala donde se exhiben peliculas')
insert into categoria (nombre,descripcion)
values('Tienda de música','Lugar donde se comercializan objetos musicales diversos')
insert into categoria (nombre,descripcion)
values('Karaoke Bar','Local donde se vende comida y se ofrece servicio de karaoke')
insert into categoria (nombre,descripcion)
values('Oficina','Departamento donde se realizan labores empresariales')
insert into categoria (nombre,descripcion)
values('Supermercado','Local donde se venden productos de uso diario')

---Etiqueta 
select*from Etiqueta order by id
insert into Etiqueta(nombre)
values('Canoa')
insert into Etiqueta(nombre)
values('Photoboot')
insert into Etiqueta(nombre)
values('Exótico')
insert into Etiqueta(nombre)
values('DeportesExtremos')
insert into Etiqueta(nombre)
values('NiceOutlook')
insert into Etiqueta(nombre)
values('CoolTrip')
insert into Etiqueta(nombre)
values('Alcohol')
insert into Etiqueta(nombre)
values('GoodMusic')
insert into Etiqueta(nombre)
values('GayProud')
insert into Etiqueta(nombre)
values('Freak')
insert into Etiqueta(nombre)
values('Games')
insert into Etiqueta(nombre)
values('Football')
insert into Etiqueta(nombre)
values('GoodPrice')
insert into Etiqueta(nombre)
values('GoodVibes')
insert into Etiqueta(nombre)
values('Frío')
insert into Etiqueta(nombre)
values('Cultural')
insert into Etiqueta(nombre)
values('México')

---Lugar
select*from Lugar order by id
insert into Lugar(nombre, longitud, latitud, descripcion, id_categoria)
values('Cabanna',78.5,90,'Local ubicado en frente de Forum',1)
insert into Lugar(nombre, longitud, latitud, descripcion, id_categoria)
values('Gamers',167.2,65,'Local de videojuegos dentro de Forum',2)
insert into Lugar(nombre, longitud, latitud, descripcion, id_categoria)
values('Parisina',126.4,32,'Local que distribuye telas de distintos tipos ubicada por la calle Hidalgo',5)
insert into lugar (nombre, longitud, latitud,descripcion,id_categoria)
values('Los Arcos',123.5,32,'Ubicado en la Avenida Xicotencal',1)
insert into lugar (nombre, longitud, latitud,descripcion,id_categoria)
values('Forum',81.6,34,'Plaza comercial que alberga diversos negocios ubicado en Parque Las Riberas',4)
insert into lugar (nombre, longitud, latitud,descripcion,id_categoria)
values('Cerveceria Chapultepec',43.54,21.3,'Local donde se comercializan bebidas embriagantes',3)
insert into lugar (nombre, longitud, latitud,descripcion,id_categoria)
values('El Grito',-107.38,21.84,'Antro ubicado en Malecon Viejo',6)
insert into lugar (nombre, longitud, latitud,descripcion,id_categoria)
values('Museo Da Vinci',11.25,43.77,'Ubicado en Florencia, Italia',11)
insert into lugar (nombre, longitud, latitud,descripcion,id_categoria)
values('Palacio de Hierro Guadalajara',-103.40,20.71,'Muebles finos y costosos a la venta',9)
insert into lugar (nombre, longitud, latitud,descripcion,id_categoria)
values('El Bull Ingles',-99.03,19.70,'Antro de la CDMX',6)
insert into lugar (nombre, longitud, latitud,descripcion,id_categoria)
values('Oak Hall',-89.85,35.10,'Tienda de ropa ubicada en Memphis, Tennessee',5)
insert into lugar (nombre, longitud, latitud,descripcion,id_categoria)
values('Masin',-107.394275,24.811078,'Museo de Arte de Sinaloa ubicado en la calle Antonio Rosales',11)
insert into lugar (nombre, longitud, latitud,descripcion,id_categoria)
values('Cinepolos La Noria',-98.223829,19.034874,'Cine ubicado en Puebla',12)
insert into lugar (nombre, longitud, latitud,descripcion,id_categoria)
values('Music Craft Ltd', -103.85,49.66,'Ubicada en  Weyburn,Canada',13)
insert into lugar (nombre, longitud, latitud,descripcion,id_categoria)
values('Sobo 151',-104.987877,39.713632,'Bar con juegos y comida',14)
insert into lugar (nombre, longitud, latitud,descripcion,id_categoria)
values('La Comer Culiacán',-93.98,35.43,'Supermercado que alberga diversos puestos',16)
insert into lugar (nombre, longitud, latitud,descripcion,id_categoria)
values('Ley Tres Rios',-107.4,24.85,'Local perteneciente a Casa Ley ubicado frente a Forum en Culiacán, Sin.',16)

---Etiqueta-Lugar
select*from Etiqueta_Lugar
insert into Etiqueta_Lugar(id_lugar,id_etiqueta)
values(15,1)
insert into Etiqueta_Lugar(id_lugar,id_etiqueta)
values(5,14)
insert into Etiqueta_Lugar(id_lugar,id_etiqueta)
values(1,6)
insert into Etiqueta_Lugar(id_lugar,id_etiqueta)
values(8,17)
insert into Etiqueta_Lugar(id_lugar,id_etiqueta)
values(2,16)
insert into Etiqueta_Lugar(id_lugar,id_etiqueta)
values(13,12)
insert into Etiqueta_Lugar(id_lugar,id_etiqueta)
values(2,1)
insert into Etiqueta_Lugar(id_lugar,id_etiqueta)
values(14,3)
insert into Etiqueta_Lugar(id_lugar,id_etiqueta)
values(15,16)
insert into Etiqueta_Lugar(id_lugar,id_etiqueta)
values(11,6)
insert into Etiqueta_Lugar(id_lugar,id_etiqueta)
values(3,14)
insert into Etiqueta_Lugar(id_lugar,id_etiqueta)
values(6,15)
insert into Etiqueta_Lugar(id_lugar,id_etiqueta)
values(4,16)
insert into Etiqueta_Lugar(id_lugar,id_etiqueta)
values(11,11)
insert into Etiqueta_Lugar(id_lugar,id_etiqueta)
values(14,6)
insert into Etiqueta_Lugar(id_lugar,id_etiqueta)
values(2,13)
insert into Etiqueta_Lugar(id_lugar,id_etiqueta)
values(13,13)
insert into Etiqueta_Lugar(id_lugar,id_etiqueta)
values(5,15)
insert into Etiqueta_Lugar(id_lugar,id_etiqueta)
values(1,17)
insert into Etiqueta_Lugar(id_lugar,id_etiqueta)
values(15,9)
insert into Etiqueta_Lugar(id_lugar,id_etiqueta)
values(9,10)
insert into Etiqueta_Lugar(id_lugar,id_etiqueta)
values(6,9)
insert into Etiqueta_Lugar(id_lugar,id_etiqueta)
values(8,16)
insert into Etiqueta_Lugar(id_lugar,id_etiqueta)
values(1,9)
insert into Etiqueta_Lugar(id_lugar,id_etiqueta)
values(12,4)
insert into Etiqueta_Lugar(id_lugar,id_etiqueta)
values(11,1)
insert into Etiqueta_Lugar(id_lugar,id_etiqueta)
values(6,11)
insert into Etiqueta_Lugar(id_lugar,id_etiqueta)
values(13,7)
insert into Etiqueta_Lugar(id_lugar,id_etiqueta)
values(6,5)
insert into Etiqueta_Lugar(id_lugar,id_etiqueta)
values(9,9)
insert into Etiqueta_Lugar(id_lugar,id_etiqueta)
values(6,16)
insert into Etiqueta_Lugar(id_lugar,id_etiqueta)
values(14,10)
insert into Etiqueta_Lugar(id_lugar,id_etiqueta)
values(7,1)
insert into Etiqueta_Lugar(id_lugar,id_etiqueta)
values(12,16)
insert into Etiqueta_Lugar(id_lugar,id_etiqueta)
values(15,11)
insert into Etiqueta_Lugar(id_lugar,id_etiqueta)
values(10,12)
insert into Etiqueta_Lugar(id_lugar,id_etiqueta)
values(7,6)
insert into Etiqueta_Lugar(id_lugar,id_etiqueta)
values(4,11)
insert into Etiqueta_Lugar(id_lugar,id_etiqueta)
values(1,1)
insert into Etiqueta_Lugar(id_lugar,id_etiqueta)
values(9,14)
insert into Etiqueta_Lugar(id_lugar,id_etiqueta)
values(10,9)
insert into Etiqueta_Lugar(id_lugar,id_etiqueta)
values(13,4)
insert into Etiqueta_Lugar(id_lugar,id_etiqueta)
values(12,12)
insert into Etiqueta_Lugar(id_lugar,id_etiqueta)
values(1,15)
insert into Etiqueta_Lugar(id_lugar,id_etiqueta)
values(6,4)
insert into Etiqueta_Lugar(id_lugar,id_etiqueta)
values(8,3)
insert into Etiqueta_Lugar(id_lugar,id_etiqueta)
values(10,1)
insert into Etiqueta_Lugar(id_lugar,id_etiqueta)
values(7,16)
insert into Etiqueta_Lugar(id_lugar,id_etiqueta)
values(3,2)
insert into Etiqueta_Lugar(id_lugar,id_etiqueta)
values(3,5)
insert into Etiqueta_Lugar(id_lugar,id_etiqueta)
values(5,11)
insert into Etiqueta_Lugar(id_lugar,id_etiqueta)
values(11,5)
insert into Etiqueta_Lugar(id_lugar,id_etiqueta)
values(8,14)
insert into Etiqueta_Lugar(id_lugar,id_etiqueta)
values(12,14)
insert into Etiqueta_Lugar(id_lugar,id_etiqueta)
values(6,7)
insert into Etiqueta_Lugar(id_lugar,id_etiqueta)
values(9,16)
insert into Etiqueta_Lugar(id_lugar,id_etiqueta)
values(13,14)
insert into Etiqueta_Lugar(id_lugar,id_etiqueta)
values(15,5)
insert into Etiqueta_Lugar(id_lugar,id_etiqueta)
values(8,1)
insert into Etiqueta_Lugar(id_lugar,id_etiqueta)
values(10,2)
insert into Etiqueta_Lugar(id_lugar,id_etiqueta)
values(8,8)
insert into Etiqueta_Lugar(id_lugar,id_etiqueta)
values(15,4)
insert into Etiqueta_Lugar(id_lugar,id_etiqueta)
values(5,5)
insert into Etiqueta_Lugar(id_lugar,id_etiqueta)
values(14,12)
insert into Etiqueta_Lugar(id_lugar,id_etiqueta)
values(4,8)
insert into Etiqueta_Lugar(id_lugar,id_etiqueta)
values(13,2)
insert into Etiqueta_Lugar(id_lugar,id_etiqueta)
values(8,12)
insert into Etiqueta_Lugar(id_lugar,id_etiqueta)
values(5,3)
insert into Etiqueta_Lugar(id_lugar,id_etiqueta)
values(12,8)
insert into Etiqueta_Lugar(id_lugar,id_etiqueta)
values(14,2)
insert into Etiqueta_Lugar(id_lugar,id_etiqueta)
values(9,2)
insert into Etiqueta_Lugar(id_lugar,id_etiqueta)
values(9,8)
insert into Etiqueta_Lugar(id_lugar,id_etiqueta)
values(10,16)
insert into Etiqueta_Lugar(id_lugar,id_etiqueta)
values(4,15)
insert into Etiqueta_Lugar(id_lugar,id_etiqueta)
values(11,9)
insert into Etiqueta_Lugar(id_lugar,id_etiqueta)
values(7,15)
insert into Etiqueta_Lugar(id_lugar,id_etiqueta)
values(6,1)
insert into Etiqueta_Lugar(id_lugar,id_etiqueta)
values(3,3)
insert into Etiqueta_Lugar(id_lugar,id_etiqueta)
values(8,2)
insert into Etiqueta_Lugar(id_lugar,id_etiqueta)
values(1,7)

---Ciudad
select*from Ciudad
insert into Ciudad(nombre)
values('Culiacán')
insert into Ciudad(nombre)
values('Mazatlán')
insert into Ciudad(nombre)
values('CD. Juarez')
insert into Ciudad(nombre)
values('New York')
insert into Ciudad(nombre)
values('CDMX')
insert into Ciudad(nombre)
values('Venecia')
insert into Ciudad(nombre)
values('Florencia')
insert into Ciudad(nombre)
values('Moscu')
insert into Ciudad(nombre)
values('Sao Paulo')
insert into Ciudad(nombre)
values('Buenos Aires')
insert into Ciudad(nombre)
values('Cartagena')

---Usuario
select*from Usuario order by id
insert into Usuario(email,nombre,nombre_usuario,contraseña,id_ciudad)
values('mp41510@hotmail.com','Alessandro Romanov','Atakito','TydpDKH6m3',3)
insert into Usuario(email,nombre,nombre_usuario,contraseña,id_ciudad)
values('bukceline@hotmail.com ','Jorge Barraza','Estabotika','12345698',3)
insert into Usuario(email,nombre,nombre_usuario,contraseña,id_ciudad)
values('zarlengod@hotmail.com','Flor Lopéz','Budespenser','TydpDKH6m3',8)
insert into Usuario(email,nombre,nombre_usuario,contraseña,id_ciudad)
values('sandeep.slg678@hotmail.com','Alessandro Bejarano','Esmodeon','trustno1',10)
insert into Usuario(email,nombre,nombre_usuario,contraseña,id_ciudad)
values('noramfuller@hotmail.com','Fernanda Rosa','SocyalyZando','EhGf6gvxUf',8)
insert into Usuario(email,nombre,nombre_usuario,contraseña,id_ciudad)
values('bangtoyib2@hotmail.com',' Sokolov','AtrapaSueños','TydpDKH6m3',4)
insert into Usuario(email,nombre,nombre_usuario,contraseña,id_ciudad)
values('andersonasantos@hotmail.com','Gerardo Sokolov','MapaFondue','iloveyou',4)
insert into Usuario(email,nombre,nombre_usuario,contraseña,id_ciudad)
values('aubreybyfield@hotmail.com','Manuel Villa','CascaLabias','3RunGL8XKd',7)
insert into Usuario(email,nombre,nombre_usuario,contraseña,id_ciudad)
values('alesganz@hotmail.com','Roxana Bejarano','BaloNoencesto','jZY5ajXBAu',5)
insert into Usuario(email,nombre,nombre_usuario,contraseña,id_ciudad)
values('ian.mcgrenaghan@hotmail.com','Jorge Conte','BaraKobima','8hPgXYnWVF',3)
insert into Usuario(email,nombre,nombre_usuario,contraseña,id_ciudad)
values('sanquel21@hotmail.com','Putin Caruso','SientoVolar','iniciar sesión',11)
insert into Usuario(email,nombre,nombre_usuario,contraseña,id_ciudad)
values('atkins618@yahoo.com','Martin Volkov','ParaSito','bH6dKgSMAT',8)
insert into Usuario(email,nombre,nombre_usuario,contraseña,id_ciudad)
values('28youngpills@yahoo.com','Jorge Quintana','Larai','starwars',4)
insert into Usuario(email,nombre,nombre_usuario,contraseña,id_ciudad)
values('armanddarkmoon08@yahoo.com','Cindy Desposorio','TartaDeFresa','hsBECMpA4n',5)
insert into Usuario(email,nombre,nombre_usuario,contraseña,id_ciudad)
values('wood0987@yahoo.com','Jennifer Sokolov','PacoJones','dragón',2)
insert into Usuario(email,nombre,nombre_usuario,contraseña,id_ciudad)
values('bloodsik@yahoo.com','Oslo Esposito','Wizo','GT58aQeCtj',8)
insert into Usuario(email,nombre,nombre_usuario,contraseña,id_ciudad)
values('naidu.sainath@yahoo.com','Pedro Esposito','Pikocha','JydATDufSt',4)
insert into Usuario(email,nombre,nombre_usuario,contraseña,id_ciudad)
values('zara.athrun@yahoo.com','Gerardo Sokolov','Xinxeto','libertad',5)
insert into Usuario(email,nombre,nombre_usuario,contraseña,id_ciudad)
values('got2scrap@yahoo.com','Fernanda Bejarano','Coquincha','V7P8ddrVh7',3)
insert into Usuario(email,nombre,nombre_usuario,contraseña,id_ciudad)
values('tigervod@yahoo.com','Alessandro Caruso','Ididoko','administrador',2)
insert into Usuario(email,nombre,nombre_usuario,contraseña,id_ciudad)
values('tiguan14@yahoo.com','Alessandro Villa','Jalash','12345678',7)
insert into Usuario(email,nombre,nombre_usuario,contraseña,id_ciudad)
values('saagar.sinha@yahoo.com','Enzo Conte','Ronstic','DHqMCXxjHh',4)
insert into Usuario(email,nombre,nombre_usuario,contraseña,id_ciudad)
values('umaralmohammed@yahoo.com','Gerardo Romanov','ChinoDuro','12345678',11)
insert into Usuario(email,nombre,nombre_usuario,contraseña,id_ciudad)
values('rohit.2241983@yahoo.com','Maria Romanov','Crackwitter','libertad',11)
insert into Usuario(email,nombre,nombre_usuario,contraseña,id_ciudad)
values('bharath.kr@yahoo.com','Alina Conte','SlashScrash','GT58aQeCtj',1)
insert into Usuario(email,nombre,nombre_usuario,contraseña,id_ciudad)
values('julio.tan@yahoo.com','Pedro Conte','AbetoAmarillo','EEVVWVB2kW',7)
insert into Usuario(email,nombre,nombre_usuario,contraseña,id_ciudad)
values('ivanbouchot@yahoo.com','Fernanda Quintana','Rolando','FH6sbBHAcn',7)
insert into Usuario(email,nombre,nombre_usuario,contraseña,id_ciudad)
values('dean.watkin@yahoo.com','Roxana Volkov','MariaVaria','abc123',7)
insert into Usuario(email,nombre,nombre_usuario,contraseña,id_ciudad)
values('ria1@yahoo.com','Martina Caruso','BronxBR','mono',5)
insert into Usuario(email,nombre,nombre_usuario,contraseña,id_ciudad)
values('revitn1@yahoo.com','Sam Conte','FlauterShiniking','1234567',8)
insert into Usuario(email,nombre,nombre_usuario,contraseña,id_ciudad)
values('shengyin1377@yahoo.com','Cindy Volkov','Bananabee','UFgr3ELyRy',1)
insert into Usuario(email,nombre,nombre_usuario,contraseña,id_ciudad)
values('carcynsmommy2008@yahoo.com','Martina Esposito','Sparrowbar','iloveyou',2)
insert into Usuario(email,nombre,nombre_usuario,contraseña,id_ciudad)
values('maggiebit@yahoo.com','Jennifer Volkov','Nannymilk','12345dfd6',11)
insert into Usuario(email,nombre,nombre_usuario,contraseña,id_ciudad)
values('hardcorekicks@yahoo.com','Alina Romanov','Marrowscout','iloveyou',1)
insert into Usuario(email,nombre,nombre_usuario,contraseña,id_ciudad)
values('riahgirl08@yahoo.com','David Caruso','Ethernalflame','qazwsx',4)
insert into Usuario(email,nombre,nombre_usuario,contraseña,id_ciudad)
values('robbynebel@yahoo.com','Cindy Barraza','Parsnipjam','sGRHCp8z9D',7)
insert into Usuario(email,nombre,nombre_usuario,contraseña,id_ciudad)
values('brickpei@yahoo.com','Martin Lopéz','LadyDivine','12345678',9)
insert into Usuario(email,nombre,nombre_usuario,contraseña,id_ciudad)
values('ekayuliyanti@yahoo.com','Roxana Barraza','GoldenHood','mono',5)
insert into Usuario(email,nombre,nombre_usuario,contraseña,id_ciudad)
values('allforanezka@yahoo.com','Jennifer Quintana','Aaronn','VfcFLSRryN',7)
insert into Usuario(email,nombre,nombre_usuario,contraseña,id_ciudad)
values('chirag.dekavadiya@outlook.com','Fernanda Bejarano','Abigail','mono',11)
insert into Usuario(email,nombre,nombre_usuario,contraseña,id_ciudad)
values('dlikens1@outlook.com','Sally Lopéz','Christye','GT58aQeCtj',2)
insert into Usuario(email,nombre,nombre_usuario,contraseña,id_ciudad)
values('eskilmoehl@outlook.com','Jennifer Osuna','MeganeMeganix','EEVVWVB2kW',4)
insert into Usuario(email,nombre,nombre_usuario,contraseña,id_ciudad)
values('groovystudio@outlook.com','Jennifer Esposito','Edna','hsBECMpA4n',9)
insert into Usuario(email,nombre,nombre_usuario,contraseña,id_ciudad)
values('sale.cashiers@outlook.com','Alessandro Esposito','EdysonBaePocopeca','iloveyou',6)
insert into Usuario(email,nombre,nombre_usuario,contraseña,id_ciudad)
values('gabe.masters@outlook.com','AlexandraFelix Barraza','Gumersinda','5h2g7ZKD3P',10)
insert into Usuario(email,nombre,nombre_usuario,contraseña,id_ciudad)
values('austintoth@outlook.com','Gerardo Barraza','Chipironazo','UFgr3ELyRy',6)
insert into Usuario(email,nombre,nombre_usuario,contraseña,id_ciudad)
values('budimansaya@outlook.com','Jennifer Quintana','Lacancamusa','V7P8ddrVh7',11)
insert into Usuario(email,nombre,nombre_usuario,contraseña,id_ciudad)
values('chopperbilld@outlook.com','Oslo Esposito','Chincheto','mq23X5PwnC',6)
insert into Usuario(email,nombre,nombre_usuario,contraseña,id_ciudad)
values('evanstender@outlook.com','Alessandro Osuna','RolloBollo','starwars',8)
insert into Usuario(email,nombre,nombre_usuario,contraseña,id_ciudad)
values('ashish.tapase@outlook.com','Alina Villa','Duca2','nWcmpVU759',5)
insert into Usuario(email,nombre,nombre_usuario,contraseña,id_ciudad)
values('syafiqbasri@outlook.com','Putin Quintana','SalsaBraba','Contraseña',3)
insert into Usuario(email,nombre,nombre_usuario,contraseña,id_ciudad)
values('tlee292@outlook.com','Alina Osuna','LunaLunera','sGAUq2jRaL',10)
insert into Usuario(email,nombre,nombre_usuario,contraseña,id_ciudad)
values('sam.winch@outlook.com','Jorge Esposito','Lilatown','sGRHCp8z9D',7)
insert into Usuario(email,nombre,nombre_usuario,contraseña,id_ciudad)
values('adamsux@outlook.com','Pedro Conte','NewYorkcitty','eapg3bVTCA',7)
insert into Usuario(email,nombre,nombre_usuario,contraseña,id_ciudad)
values('kooty86@outlook.com','Alina Villa','BarishAracne','12345678',5)
insert into Usuario(email,nombre,nombre_usuario,contraseña,id_ciudad)
values('curtis.danielle@outlook.com','Putin Sokolov','WinOrDie','starwars',9)
insert into Usuario(email,nombre,nombre_usuario,contraseña,id_ciudad)
values('hafshah247@outlook.com','Cindy Romanov','LalaYPo','haZNMjFBtK',1)
insert into Usuario(email,nombre,nombre_usuario,contraseña,id_ciudad)
values('greg.kleiman@outlook.com','Fernanda Romanov','FumaoRevientaBerreo','FeV2qyCrwE',7)
insert into Usuario(email,nombre,nombre_usuario,contraseña,id_ciudad)
values('amymgw@outlook.com','Martina Caruso','Quemasmeda','EhGf6gvxUf',10)
insert into Usuario(email,nombre,nombre_usuario,contraseña,id_ciudad)
values('lolasek123@outlook.com','Jorge Quintana','Jesuchisto','jXQfRLzSjW',2)
insert into Usuario(email,nombre,nombre_usuario,contraseña,id_ciudad)
values('bogatova@outlook.com','Martina Villa','Callatuboca','starwars',6)
insert into Usuario(email,nombre,nombre_usuario,contraseña,id_ciudad)
values('bernardchoo23@outlook.com','Enzo Lopéz','Comprateunmono','P6yGJSYRDt',9)
insert into Usuario(email,nombre,nombre_usuario,contraseña,id_ciudad)
values('bongden987@gmail.com',' Villa','Txmaforo','P6yGJSYRDt',11)
insert into Usuario(email,nombre,nombre_usuario,contraseña,id_ciudad)
values('blahblah3399@gmail.com','Pedro Conte','Porlasnubes','starwars',7)
insert into Usuario(email,nombre,nombre_usuario,contraseña,id_ciudad)
values('katierose1@gmail.com','Enzo Osuna','Carapapa','eGpZLXFW4u',6)
insert into Usuario(email,nombre,nombre_usuario,contraseña,id_ciudad)
values('tom.roe@gmail.com','Gerardo Conte','Marcoscorron','haZNMjFBtK',5)
insert into Usuario(email,nombre,nombre_usuario,contraseña,id_ciudad)
values('patrick.animus@gmail.com',' Romanov','ChincheBinche','CWPEGSmJ7G',2)
insert into Usuario(email,nombre,nombre_usuario,contraseña,id_ciudad)
values('snazzysauce@gmail.com','Eros Lopéz','VaAserQueNo','nWcmpVU759',7)
insert into Usuario(email,nombre,nombre_usuario,contraseña,id_ciudad)
values('bloomingfreesia@gmail.com','Roxana Caruso','RataRatera','maestro',3)
insert into Usuario(email,nombre,nombre_usuario,contraseña,id_ciudad)
values('suploading@gmail.com','Alessandro Volkov','AzufreAmarillo','JydATDufSt',1)
insert into Usuario(email,nombre,nombre_usuario,contraseña,id_ciudad)
values('marcocappi@gmail.com','Beatrice Bejarano','MoscaCatiosca','fútbol',10)
insert into Usuario(email,nombre,nombre_usuario,contraseña,id_ciudad)
values('7h3.w1z4rd@gmail.com','Maria Quintana','PulgonPuntoComAnabanana','anD4NPz3V2',11)
insert into Usuario(email,nombre,nombre_usuario,contraseña,id_ciudad)
values('firefighterswife04@gmail.com','Eros Volkov','Anateama','nWcmpVU759',8)
insert into Usuario(email,nombre,nombre_usuario,contraseña,id_ciudad)
values('kcabot@gmail.com',' Quintana','Almadeestrella','zbrRWW9env',7)
insert into Usuario(email,nombre,nombre_usuario,contraseña,id_ciudad)
values('rubensalves.junior@gmail.com',' Caruso','Dulcesueño','CWPEGSmJ7G',5)
insert into Usuario(email,nombre,nombre_usuario,contraseña,id_ciudad)
values('fgunstad@gmail.com','Alessandro Volkov','Olvidaminombre','bienvenido',9)
insert into Usuario(email,nombre,nombre_usuario,contraseña,id_ciudad)
values('rocingcn@gmail.com','Martin Villa','Musadeazucar','M92jD7ebV4',9)
insert into Usuario(email,nombre,nombre_usuario,contraseña,id_ciudad)
values('johnjp100@gmail.com','Martina Romanov','Flordelis','3RunGL8XKd',1)
insert into Usuario(email,nombre,nombre_usuario,contraseña,id_ciudad)
values('akromosono@gmail.com','Pedro Sokolov','Flordeloto','6vvCF4d7cH',4)
insert into Usuario(email,nombre,nombre_usuario,contraseña,id_ciudad)
values('vankrezen@gmail.com','Beatrice Desposorio','MardeLuna','jZY5ajXBAu',5)
insert into Usuario(email,nombre,nombre_usuario,contraseña,id_ciudad)
values('adawdwad23@gmail.com','Maria Esposito','BrillodeAzar','sGRHCp8z9D',11)
insert into Usuario(email,nombre,nombre_usuario,contraseña,id_ciudad)
values('balaji070178@gmail.com',' Romanov','AzucaryMiel','yMLtAkpnhP',2)
insert into Usuario(email,nombre,nombre_usuario,contraseña,id_ciudad)
values('themyth.aziz@gmail.com','Maria Esposito','Lanabit','trustno1',3)
insert into Usuario(email,nombre,nombre_usuario,contraseña,id_ciudad)
values('arlissnyc@gmail.com','Maria Osuna','TatyMorena','anD4NPz3V2',1)
insert into Usuario(email,nombre,nombre_usuario,contraseña,id_ciudad)
values('borisol55@gmail.com','Fernanda Desposorio','ColordelaLuna','mono',6)
insert into Usuario(email,nombre,nombre_usuario,contraseña,id_ciudad)
values('hipes.dennis@gmail.com','Jennifer Desposorio','CristalRojoFuegoLakitschy','abc123',8)
insert into Usuario(email,nombre,nombre_usuario,contraseña,id_ciudad)
values('jakarri30@gmail.com','Sally Conte','Oakdog','fútbol',2)
insert into Usuario(email,nombre,nombre_usuario,contraseña,id_ciudad)
values('puppyspew@gmail.com','Pedro Barraza','Antimainstream','123456',8)
insert into Usuario(email,nombre,nombre_usuario,contraseña,id_ciudad)
values('mukesh.tiwari962@gmail.com','Pedro Osuna','Grassfed','anD4NPz3V2',3)
insert into Usuario(email,nombre,nombre_usuario,contraseña,id_ciudad)
values('joyel4u@gmail.com','Martin Osuna','Siryquinoa','administrador',10)
insert into Usuario(email,nombre,nombre_usuario,contraseña,id_ciudad)
values('ajiyeee@gmail.com','Cindy Conte','Gafasdepasta','V7P8ddrVh7',1)
insert into Usuario(email,nombre,nombre_usuario,contraseña,id_ciudad)
values('kirbylau2@gmail.com','David Rosa','Khalifeh','iloveyou',7)
insert into Usuario(email,nombre,nombre_usuario,contraseña,id_ciudad)
values('kmanoj11@gmail.com','Eros Caruso','Vinilover','qqCpt8Pnwh',11)
insert into Usuario(email,nombre,nombre_usuario,contraseña,id_ciudad)
values('carlosd2580@gmail.com','Maria Caruso','Abataste','dragón',9)
insert into Usuario(email,nombre,nombre_usuario,contraseña,id_ciudad)
values('bowlton.garcia@gmail.com','Alessandro Sokolov','Lulonomero','haZNMjFBtK',9)
insert into Usuario(email,nombre,nombre_usuario,contraseña,id_ciudad)
values('browneyedgirl209@gmail.com','Fernanda Quintana','Bartolome','FH6sbBHAcn',1)
insert into Usuario(email,nombre,nombre_usuario,contraseña,id_ciudad)
values('evenkillband@gmail.com','Fernanda Lopéz','DragoEldos','fwLhkMYwaS',6)
insert into Usuario(email,nombre,nombre_usuario,contraseña,id_ciudad)
values('johnny.r.stivers@gmail.com','Eros Barraza','Okkdor','Qtd6YTbVZ5',9)
insert into Usuario(email,nombre,nombre_usuario,contraseña,id_ciudad)
values('hoare.marc@gmail.com','Pedro Caruso','Mordorduro','JydATDufSt',10)
insert into Usuario(email,nombre,nombre_usuario,contraseña,id_ciudad)
values('chacaldesbalcans@gmail.com','Jennifer Romanov','JobssySalsipuedes','administrador',4)
insert into Usuario(email,nombre,nombre_usuario,contraseña,id_ciudad)
values('mpfaulds@gmail.com','Alina Esposito','Nomesigas','5h2g7ZKD3P',6)
insert into Usuario(email,nombre,nombre_usuario,contraseña,id_ciudad)
values('danhelge@gmail.com','Martin Volkov','Huyedeaqui','abc123',3)
insert into Usuario(email,nombre,nombre_usuario,contraseña,id_ciudad)
values('bheatrizpitta@gmail.com','Oslo Osuna','Tiratealvolcan','TydpDKH6m3',3)
insert into Usuario(email,nombre,nombre_usuario,contraseña,id_ciudad)
values('nits.ud44@gmail.com','Martina Caruso','Tugemela','M92jD7ebV4',2)
insert into Usuario(email,nombre,nombre_usuario,contraseña,id_ciudad)
values('irm1983@gmail.com','Alina Volkov','ElCuatroCuadras','djVDQUDU7Z',3)
insert into Usuario(email,nombre,nombre_usuario,contraseña,id_ciudad)
values('mrl.mohan2@gmail.com','Sally Barraza','OdioCuatroCuadras','123456',8)
insert into Usuario(email,nombre,nombre_usuario,contraseña,id_ciudad)
values('niallparkes@gmail.com','AlexandraFelix Villa','Quetefollow','qazwsx',8)
insert into Usuario(email,nombre,nombre_usuario,contraseña,id_ciudad)
values('ykonrad@gmail.com','Fernanda Volkov','VivaFacebook','FeV2qyCrwE',8)
insert into Usuario(email,nombre,nombre_usuario,contraseña,id_ciudad)
values('rdlcamarillas@gmail.com','David Esposito','Nuncamesigas','bienvenido',5)
insert into Usuario(email,nombre,nombre_usuario,contraseña,id_ciudad)
values('gmontysgirl@gmail.com','Oslo Osuna','VeteyJodete','iloveyou',4)
insert into Usuario(email,nombre,nombre_usuario,contraseña,id_ciudad)
values('raecberry@gmail.com','David Desposorio','LaQuintaCalle','qazwsx',3)
insert into Usuario(email,nombre,nombre_usuario,contraseña,id_ciudad)
values('davidbnz@gmail.com','Oslo Osuna','OdioMiFace','UkYX2Y8YLK',6)
insert into Usuario(email,nombre,nombre_usuario,contraseña,id_ciudad)
values('erangel330@gmail.com','Gerardo Sokolov','ParecesUnMono','hsBECMpA4n',6)
insert into Usuario(email,nombre,nombre_usuario,contraseña,id_ciudad)
values('kenneth.myklebust@gmail.com','Cindy Quintana','LalaLoloyLilo','qqCpt8Pnwh',1)

---Checkin
select*from Checkin
declare @diferenciatiempo int=datediff(MILLISECOND,'00:00:00','23:59:59')
declare @inicio date='2015-02-18'
declare @diferenciadias int=datediff(day,@inicio,getdate())
insert into checkin(lugar_id,usuario_id,comentario,fecha,hora,valoracion)
values(13,108,'sdsd',DATEADD(day,rand()*(@diferenciadias-1+1),@inicio),convert(time,DATEADD(MILLISECOND,rand()*(@diferenciatiempo+1),'00:00:00')),1.1)
insert into checkin(lugar_id,usuario_id,comentario,fecha,hora,valoracion)
values(5,46,'sdsd',DATEADD(day,rand()*(@diferenciadias-1+1),@inicio),convert(time,DATEADD(MILLISECOND,rand()*(@diferenciatiempo+1),'00:00:00')),4.2)
insert into checkin(lugar_id,usuario_id,comentario,fecha,hora,valoracion)
values(2,70,'sdsd',DATEADD(day,rand()*(@diferenciadias-1+1),@inicio),convert(time,DATEADD(MILLISECOND,rand()*(@diferenciatiempo+1),'00:00:00')),3.9)
insert into checkin(lugar_id,usuario_id,comentario,fecha,hora,valoracion)
values(8,26,'sdsd',DATEADD(day,rand()*(@diferenciadias-1+1),@inicio),convert(time,DATEADD(MILLISECOND,rand()*(@diferenciatiempo+1),'00:00:00')),4.1)
insert into checkin(lugar_id,usuario_id,comentario,fecha,hora,valoracion)
values(7,4,'sdsd',DATEADD(day,rand()*(@diferenciadias-1+1),@inicio),convert(time,DATEADD(MILLISECOND,rand()*(@diferenciatiempo+1),'00:00:00')),0.9)
insert into checkin(lugar_id,usuario_id,comentario,fecha,hora,valoracion)
values(3,49,'sdsd',DATEADD(day,rand()*(@diferenciadias-1+1),@inicio),convert(time,DATEADD(MILLISECOND,rand()*(@diferenciatiempo+1),'00:00:00')),3.6)
insert into checkin(lugar_id,usuario_id,comentario,fecha,hora,valoracion)
values(7,86,'sdsd',DATEADD(day,rand()*(@diferenciadias-1+1),@inicio),convert(time,DATEADD(MILLISECOND,rand()*(@diferenciatiempo+1),'00:00:00')),4.9)
insert into checkin(lugar_id,usuario_id,comentario,fecha,hora,valoracion)
values(14,35,'sdsd',DATEADD(day,rand()*(@diferenciadias-1+1),@inicio),convert(time,DATEADD(MILLISECOND,rand()*(@diferenciatiempo+1),'00:00:00')),3.9)
insert into checkin(lugar_id,usuario_id,comentario,fecha,hora,valoracion)
values(14,12,'sdsd',DATEADD(day,rand()*(@diferenciadias-1+1),@inicio),convert(time,DATEADD(MILLISECOND,rand()*(@diferenciatiempo+1),'00:00:00')),1.1)
insert into checkin(lugar_id,usuario_id,comentario,fecha,hora,valoracion)
values(14,78,'sdsd',DATEADD(day,rand()*(@diferenciadias-1+1),@inicio),convert(time,DATEADD(MILLISECOND,rand()*(@diferenciatiempo+1),'00:00:00')),4.5)
insert into checkin(lugar_id,usuario_id,comentario,fecha,hora,valoracion)
values(11,96,'sdsd',DATEADD(day,rand()*(@diferenciadias-1+1),@inicio),convert(time,DATEADD(MILLISECOND,rand()*(@diferenciatiempo+1),'00:00:00')),1.9)
insert into checkin(lugar_id,usuario_id,comentario,fecha,hora,valoracion)
values(13,106,'sdsd',DATEADD(day,rand()*(@diferenciadias-1+1),@inicio),convert(time,DATEADD(MILLISECOND,rand()*(@diferenciatiempo+1),'00:00:00')),5)
insert into checkin(lugar_id,usuario_id,comentario,fecha,hora,valoracion)
values(4,48,'sdsd',DATEADD(day,rand()*(@diferenciadias-1+1),@inicio),convert(time,DATEADD(MILLISECOND,rand()*(@diferenciatiempo+1),'00:00:00')),0.1)
insert into checkin(lugar_id,usuario_id,comentario,fecha,hora,valoracion)
values(3,60,'sdsd',DATEADD(day,rand()*(@diferenciadias-1+1),@inicio),convert(time,DATEADD(MILLISECOND,rand()*(@diferenciatiempo+1),'00:00:00')),2.1)
insert into checkin(lugar_id,usuario_id,comentario,fecha,hora,valoracion)
values(1,48,'sdsd',DATEADD(day,rand()*(@diferenciadias-1+1),@inicio),convert(time,DATEADD(MILLISECOND,rand()*(@diferenciatiempo+1),'00:00:00')),0.1)
insert into checkin(lugar_id,usuario_id,comentario,fecha,hora,valoracion)
values(1,71,'sdsd',DATEADD(day,rand()*(@diferenciadias-1+1),@inicio),convert(time,DATEADD(MILLISECOND,rand()*(@diferenciatiempo+1),'00:00:00')),1.9)
insert into checkin(lugar_id,usuario_id,comentario,fecha,hora,valoracion)
values(1,97,'sdsd',DATEADD(day,rand()*(@diferenciadias-1+1),@inicio),convert(time,DATEADD(MILLISECOND,rand()*(@diferenciatiempo+1),'00:00:00')),1.6)
insert into checkin(lugar_id,usuario_id,comentario,fecha,hora,valoracion)
values(2,44,'sdsd',DATEADD(day,rand()*(@diferenciadias-1+1),@inicio),convert(time,DATEADD(MILLISECOND,rand()*(@diferenciatiempo+1),'00:00:00')),4.8)
insert into checkin(lugar_id,usuario_id,comentario,fecha,hora,valoracion)
values(15,3,'sdsd',DATEADD(day,rand()*(@diferenciadias-1+1),@inicio),convert(time,DATEADD(MILLISECOND,rand()*(@diferenciatiempo+1),'00:00:00')),4.9)
insert into checkin(lugar_id,usuario_id,comentario,fecha,hora,valoracion)
values(10,71,'sdsd',DATEADD(day,rand()*(@diferenciadias-1+1),@inicio),convert(time,DATEADD(MILLISECOND,rand()*(@diferenciatiempo+1),'00:00:00')),1.3)
insert into checkin(lugar_id,usuario_id,comentario,fecha,hora,valoracion)
values(6,23,'sdsd',DATEADD(day,rand()*(@diferenciadias-1+1),@inicio),convert(time,DATEADD(MILLISECOND,rand()*(@diferenciatiempo+1),'00:00:00')),0.6)
insert into checkin(lugar_id,usuario_id,comentario,fecha,hora,valoracion)
values(1,51,'sdsd',DATEADD(day,rand()*(@diferenciadias-1+1),@inicio),convert(time,DATEADD(MILLISECOND,rand()*(@diferenciatiempo+1),'00:00:00')),0.3)
insert into checkin(lugar_id,usuario_id,comentario,fecha,hora,valoracion)
values(3,53,'sdsd',DATEADD(day,rand()*(@diferenciadias-1+1),@inicio),convert(time,DATEADD(MILLISECOND,rand()*(@diferenciatiempo+1),'00:00:00')),4.6)
insert into checkin(lugar_id,usuario_id,comentario,fecha,hora,valoracion)
values(15,24,'sdsd',DATEADD(day,rand()*(@diferenciadias-1+1),@inicio),convert(time,DATEADD(MILLISECOND,rand()*(@diferenciatiempo+1),'00:00:00')),5)
insert into checkin(lugar_id,usuario_id,comentario,fecha,hora,valoracion)
values(10,89,'sdsd',DATEADD(day,rand()*(@diferenciadias-1+1),@inicio),convert(time,DATEADD(MILLISECOND,rand()*(@diferenciatiempo+1),'00:00:00')),3.4)
insert into checkin(lugar_id,usuario_id,comentario,fecha,hora,valoracion)
values(5,61,'sdsd',DATEADD(day,rand()*(@diferenciadias-1+1),@inicio),convert(time,DATEADD(MILLISECOND,rand()*(@diferenciatiempo+1),'00:00:00')),3.9)
insert into checkin(lugar_id,usuario_id,comentario,fecha,hora,valoracion)
values(1,97,'sdsd',DATEADD(day,rand()*(@diferenciadias-1+1),@inicio),convert(time,DATEADD(MILLISECOND,rand()*(@diferenciatiempo+1),'00:00:00')),4.8)
insert into checkin(lugar_id,usuario_id,comentario,fecha,hora,valoracion)
values(9,12,'sdsd',DATEADD(day,rand()*(@diferenciadias-1+1),@inicio),convert(time,DATEADD(MILLISECOND,rand()*(@diferenciatiempo+1),'00:00:00')),1.9)
insert into checkin(lugar_id,usuario_id,comentario,fecha,hora,valoracion)
values(11,26,'sdsd',DATEADD(day,rand()*(@diferenciadias-1+1),@inicio),convert(time,DATEADD(MILLISECOND,rand()*(@diferenciatiempo+1),'00:00:00')),3.3)
insert into checkin(lugar_id,usuario_id,comentario,fecha,hora,valoracion)
values(11,10,'sdsd',DATEADD(day,rand()*(@diferenciadias-1+1),@inicio),convert(time,DATEADD(MILLISECOND,rand()*(@diferenciatiempo+1),'00:00:00')),1.4)
insert into checkin(lugar_id,usuario_id,comentario,fecha,hora,valoracion)
values(4,110,'sdsd',DATEADD(day,rand()*(@diferenciadias-1+1),@inicio),convert(time,DATEADD(MILLISECOND,rand()*(@diferenciatiempo+1),'00:00:00')),1.2)
insert into checkin(lugar_id,usuario_id,comentario,fecha,hora,valoracion)
values(6,15,'sdsd',DATEADD(day,rand()*(@diferenciadias-1+1),@inicio),convert(time,DATEADD(MILLISECOND,rand()*(@diferenciatiempo+1),'00:00:00')),1.6)
insert into checkin(lugar_id,usuario_id,comentario,fecha,hora,valoracion)
values(11,45,'sdsd',DATEADD(day,rand()*(@diferenciadias-1+1),@inicio),convert(time,DATEADD(MILLISECOND,rand()*(@diferenciatiempo+1),'00:00:00')),4.3)
insert into checkin(lugar_id,usuario_id,comentario,fecha,hora,valoracion)
values(14,26,'sdsd',DATEADD(day,rand()*(@diferenciadias-1+1),@inicio),convert(time,DATEADD(MILLISECOND,rand()*(@diferenciatiempo+1),'00:00:00')),2.8)
insert into checkin(lugar_id,usuario_id,comentario,fecha,hora,valoracion)
values(11,105,'sdsd',DATEADD(day,rand()*(@diferenciadias-1+1),@inicio),convert(time,DATEADD(MILLISECOND,rand()*(@diferenciatiempo+1),'00:00:00')),1)
insert into checkin(lugar_id,usuario_id,comentario,fecha,hora,valoracion)
values(14,47,'sdsd',DATEADD(day,rand()*(@diferenciadias-1+1),@inicio),convert(time,DATEADD(MILLISECOND,rand()*(@diferenciatiempo+1),'00:00:00')),4.4)
insert into checkin(lugar_id,usuario_id,comentario,fecha,hora,valoracion)
values(9,69,'sdsd',DATEADD(day,rand()*(@diferenciadias-1+1),@inicio),convert(time,DATEADD(MILLISECOND,rand()*(@diferenciatiempo+1),'00:00:00')),4.6)
insert into checkin(lugar_id,usuario_id,comentario,fecha,hora,valoracion)
values(2,85,'sdsd',DATEADD(day,rand()*(@diferenciadias-1+1),@inicio),convert(time,DATEADD(MILLISECOND,rand()*(@diferenciatiempo+1),'00:00:00')),1.6)
insert into checkin(lugar_id,usuario_id,comentario,fecha,hora,valoracion)
values(2,6,'sdsd',DATEADD(day,rand()*(@diferenciadias-1+1),@inicio),convert(time,DATEADD(MILLISECOND,rand()*(@diferenciatiempo+1),'00:00:00')),2.1)
insert into checkin(lugar_id,usuario_id,comentario,fecha,hora,valoracion)
values(13,46,'sdsd',DATEADD(day,rand()*(@diferenciadias-1+1),@inicio),convert(time,DATEADD(MILLISECOND,rand()*(@diferenciatiempo+1),'00:00:00')),3.7)
insert into checkin(lugar_id,usuario_id,comentario,fecha,hora,valoracion)
values(4,107,'sdsd',DATEADD(day,rand()*(@diferenciadias-1+1),@inicio),convert(time,DATEADD(MILLISECOND,rand()*(@diferenciatiempo+1),'00:00:00')),3.5)
insert into checkin(lugar_id,usuario_id,comentario,fecha,hora,valoracion)
values(3,36,'sdsd',DATEADD(day,rand()*(@diferenciadias-1+1),@inicio),convert(time,DATEADD(MILLISECOND,rand()*(@diferenciatiempo+1),'00:00:00')),3.5)
insert into checkin(lugar_id,usuario_id,comentario,fecha,hora,valoracion)
values(9,58,'sdsd',DATEADD(day,rand()*(@diferenciadias-1+1),@inicio),convert(time,DATEADD(MILLISECOND,rand()*(@diferenciatiempo+1),'00:00:00')),1.7)
insert into checkin(lugar_id,usuario_id,comentario,fecha,hora,valoracion)
values(10,3,'sdsd',DATEADD(day,rand()*(@diferenciadias-1+1),@inicio),convert(time,DATEADD(MILLISECOND,rand()*(@diferenciatiempo+1),'00:00:00')),4.9)
insert into checkin(lugar_id,usuario_id,comentario,fecha,hora,valoracion)
values(11,108,'sdsd',DATEADD(day,rand()*(@diferenciadias-1+1),@inicio),convert(time,DATEADD(MILLISECOND,rand()*(@diferenciatiempo+1),'00:00:00')),0.1)
insert into checkin(lugar_id,usuario_id,comentario,fecha,hora,valoracion)
values(2,53,'sdsd',DATEADD(day,rand()*(@diferenciadias-1+1),@inicio),convert(time,DATEADD(MILLISECOND,rand()*(@diferenciatiempo+1),'00:00:00')),1.7)
insert into checkin(lugar_id,usuario_id,comentario,fecha,hora,valoracion)
values(10,78,'sdsd',DATEADD(day,rand()*(@diferenciadias-1+1),@inicio),convert(time,DATEADD(MILLISECOND,rand()*(@diferenciatiempo+1),'00:00:00')),3.3)
insert into checkin(lugar_id,usuario_id,comentario,fecha,hora,valoracion)
values(6,56,'sdsd',DATEADD(day,rand()*(@diferenciadias-1+1),@inicio),convert(time,DATEADD(MILLISECOND,rand()*(@diferenciatiempo+1),'00:00:00')),4.4)
insert into checkin(lugar_id,usuario_id,comentario,fecha,hora,valoracion)
values(12,71,'sdsd',DATEADD(day,rand()*(@diferenciadias-1+1),@inicio),convert(time,DATEADD(MILLISECOND,rand()*(@diferenciatiempo+1),'00:00:00')),2.9)
insert into checkin(lugar_id,usuario_id,comentario,fecha,hora,valoracion)
values(1,101,'sdsd',DATEADD(day,rand()*(@diferenciadias-1+1),@inicio),convert(time,DATEADD(MILLISECOND,rand()*(@diferenciatiempo+1),'00:00:00')),0.6)
insert into checkin(lugar_id,usuario_id,comentario,fecha,hora,valoracion)
values(12,106,'sdsd',DATEADD(day,rand()*(@diferenciadias-1+1),@inicio),convert(time,DATEADD(MILLISECOND,rand()*(@diferenciatiempo+1),'00:00:00')),4.2)
insert into checkin(lugar_id,usuario_id,comentario,fecha,hora,valoracion)
values(3,14,'sdsd',DATEADD(day,rand()*(@diferenciadias-1+1),@inicio),convert(time,DATEADD(MILLISECOND,rand()*(@diferenciatiempo+1),'00:00:00')),4.7)
insert into checkin(lugar_id,usuario_id,comentario,fecha,hora,valoracion)
values(15,37,'sdsd',DATEADD(day,rand()*(@diferenciadias-1+1),@inicio),convert(time,DATEADD(MILLISECOND,rand()*(@diferenciatiempo+1),'00:00:00')),2.2)
insert into checkin(lugar_id,usuario_id,comentario,fecha,hora,valoracion)
values(6,69,'sdsd',DATEADD(day,rand()*(@diferenciadias-1+1),@inicio),convert(time,DATEADD(MILLISECOND,rand()*(@diferenciatiempo+1),'00:00:00')),2.5)
insert into checkin(lugar_id,usuario_id,comentario,fecha,hora,valoracion)
values(10,114,'sdsd',DATEADD(day,rand()*(@diferenciadias-1+1),@inicio),convert(time,DATEADD(MILLISECOND,rand()*(@diferenciatiempo+1),'00:00:00')),0.5)
insert into checkin(lugar_id,usuario_id,comentario,fecha,hora,valoracion)
values(7,108,'sdsd',DATEADD(day,rand()*(@diferenciadias-1+1),@inicio),convert(time,DATEADD(MILLISECOND,rand()*(@diferenciatiempo+1),'00:00:00')),2.7)
insert into checkin(lugar_id,usuario_id,comentario,fecha,hora,valoracion)
values(9,108,'sdsd',DATEADD(day,rand()*(@diferenciadias-1+1),@inicio),convert(time,DATEADD(MILLISECOND,rand()*(@diferenciatiempo+1),'00:00:00')),4.5)
insert into checkin(lugar_id,usuario_id,comentario,fecha,hora,valoracion)
values(13,40,'sdsd',DATEADD(day,rand()*(@diferenciadias-1+1),@inicio),convert(time,DATEADD(MILLISECOND,rand()*(@diferenciatiempo+1),'00:00:00')),0.3)
insert into checkin(lugar_id,usuario_id,comentario,fecha,hora,valoracion)
values(9,80,'sdsd',DATEADD(day,rand()*(@diferenciadias-1+1),@inicio),convert(time,DATEADD(MILLISECOND,rand()*(@diferenciatiempo+1),'00:00:00')),4.8)
insert into checkin(lugar_id,usuario_id,comentario,fecha,hora,valoracion)
values(9,111,'sdsd',DATEADD(day,rand()*(@diferenciadias-1+1),@inicio),convert(time,DATEADD(MILLISECOND,rand()*(@diferenciatiempo+1),'00:00:00')),2.4)
insert into checkin(lugar_id,usuario_id,comentario,fecha,hora,valoracion)
values(12,84,'sdsd',DATEADD(day,rand()*(@diferenciadias-1+1),@inicio),convert(time,DATEADD(MILLISECOND,rand()*(@diferenciatiempo+1),'00:00:00')),3.8)
insert into checkin(lugar_id,usuario_id,comentario,fecha,hora,valoracion)
values(6,59,'sdsd',DATEADD(day,rand()*(@diferenciadias-1+1),@inicio),convert(time,DATEADD(MILLISECOND,rand()*(@diferenciatiempo+1),'00:00:00')),4.9)
insert into checkin(lugar_id,usuario_id,comentario,fecha,hora,valoracion)
values(7,19,'sdsd',DATEADD(day,rand()*(@diferenciadias-1+1),@inicio),convert(time,DATEADD(MILLISECOND,rand()*(@diferenciatiempo+1),'00:00:00')),5.0)
insert into checkin(lugar_id,usuario_id,comentario,fecha,hora,valoracion)
values(4,88,'sdsd',DATEADD(day,rand()*(@diferenciadias-1+1),@inicio),convert(time,DATEADD(MILLISECOND,rand()*(@diferenciatiempo+1),'00:00:00')),0.1)
insert into checkin(lugar_id,usuario_id,comentario,fecha,hora,valoracion)
values(3,31,'sdsd',DATEADD(day,rand()*(@diferenciadias-1+1),@inicio),convert(time,DATEADD(MILLISECOND,rand()*(@diferenciatiempo+1),'00:00:00')),4.1)
insert into checkin(lugar_id,usuario_id,comentario,fecha,hora,valoracion)
values(8,92,'sdsd',DATEADD(day,rand()*(@diferenciadias-1+1),@inicio),convert(time,DATEADD(MILLISECOND,rand()*(@diferenciatiempo+1),'00:00:00')),2.9)
insert into checkin(lugar_id,usuario_id,comentario,fecha,hora,valoracion)
values(4,87,'sdsd',DATEADD(day,rand()*(@diferenciadias-1+1),@inicio),convert(time,DATEADD(MILLISECOND,rand()*(@diferenciatiempo+1),'00:00:00')),3.6)
insert into checkin(lugar_id,usuario_id,comentario,fecha,hora,valoracion)
values(4,64,'sdsd',DATEADD(day,rand()*(@diferenciadias-1+1),@inicio),convert(time,DATEADD(MILLISECOND,rand()*(@diferenciatiempo+1),'00:00:00')),2.7)
insert into checkin(lugar_id,usuario_id,comentario,fecha,hora,valoracion)
values(14,86,'sdsd',DATEADD(day,rand()*(@diferenciadias-1+1),@inicio),convert(time,DATEADD(MILLISECOND,rand()*(@diferenciatiempo+1),'00:00:00')),1.8)
insert into checkin(lugar_id,usuario_id,comentario,fecha,hora,valoracion)
values(13,19,'sdsd',DATEADD(day,rand()*(@diferenciadias-1+1),@inicio),convert(time,DATEADD(MILLISECOND,rand()*(@diferenciatiempo+1),'00:00:00')),4)
insert into checkin(lugar_id,usuario_id,comentario,fecha,hora,valoracion)
values(12,25,'sdsd',DATEADD(day,rand()*(@diferenciadias-1+1),@inicio),convert(time,DATEADD(MILLISECOND,rand()*(@diferenciatiempo+1),'00:00:00')),1.2)
insert into checkin(lugar_id,usuario_id,comentario,fecha,hora,valoracion)
values(3,55,'sdsd',DATEADD(day,rand()*(@diferenciadias-1+1),@inicio),convert(time,DATEADD(MILLISECOND,rand()*(@diferenciatiempo+1),'00:00:00')),0.6)
insert into checkin(lugar_id,usuario_id,comentario,fecha,hora,valoracion)
values(13,26,'sdsd',DATEADD(day,rand()*(@diferenciadias-1+1),@inicio),convert(time,DATEADD(MILLISECOND,rand()*(@diferenciatiempo+1),'00:00:00')),1)
insert into checkin(lugar_id,usuario_id,comentario,fecha,hora,valoracion)
values(2,30,'sdsd',DATEADD(day,rand()*(@diferenciadias-1+1),@inicio),convert(time,DATEADD(MILLISECOND,rand()*(@diferenciatiempo+1),'00:00:00')),2.8)
insert into checkin(lugar_id,usuario_id,comentario,fecha,hora,valoracion)
values(3,15,'sdsd',DATEADD(day,rand()*(@diferenciadias-1+1),@inicio),convert(time,DATEADD(MILLISECOND,rand()*(@diferenciatiempo+1),'00:00:00')),3)
insert into checkin(lugar_id,usuario_id,comentario,fecha,hora,valoracion)
values(4,19,'sdsd',DATEADD(day,rand()*(@diferenciadias-1+1),@inicio),convert(time,DATEADD(MILLISECOND,rand()*(@diferenciatiempo+1),'00:00:00')),5)
insert into checkin(lugar_id,usuario_id,comentario,fecha,hora,valoracion)
values(11,45,'sdsd',DATEADD(day,rand()*(@diferenciadias-1+1),@inicio),convert(time,DATEADD(MILLISECOND,rand()*(@diferenciatiempo+1),'00:00:00')),0.7)
insert into checkin(lugar_id,usuario_id,comentario,fecha,hora,valoracion)
values(10,81,'sdsd',DATEADD(day,rand()*(@diferenciadias-1+1),@inicio),convert(time,DATEADD(MILLISECOND,rand()*(@diferenciatiempo+1),'00:00:00')),1.9)
insert into checkin(lugar_id,usuario_id,comentario,fecha,hora,valoracion)
values(10,80,'sdsd',DATEADD(day,rand()*(@diferenciadias-1+1),@inicio),convert(time,DATEADD(MILLISECOND,rand()*(@diferenciatiempo+1),'00:00:00')),3.6)
insert into checkin(lugar_id,usuario_id,comentario,fecha,hora,valoracion)
values(8,45,'sdsd',DATEADD(day,rand()*(@diferenciadias-1+1),@inicio),convert(time,DATEADD(MILLISECOND,rand()*(@diferenciatiempo+1),'00:00:00')),1)
insert into checkin(lugar_id,usuario_id,comentario,fecha,hora,valoracion)
values(14,46,'sdsd',DATEADD(day,rand()*(@diferenciadias-1+1),@inicio),convert(time,DATEADD(MILLISECOND,rand()*(@diferenciatiempo+1),'00:00:00')),0.3)
insert into checkin(lugar_id,usuario_id,comentario,fecha,hora,valoracion)
values(5,105,'sdsd',DATEADD(day,rand()*(@diferenciadias-1+1),@inicio),convert(time,DATEADD(MILLISECOND,rand()*(@diferenciatiempo+1),'00:00:00')),2.1)
insert into checkin(lugar_id,usuario_id,comentario,fecha,hora,valoracion)
values(9,52,'sdsd',DATEADD(day,rand()*(@diferenciadias-1+1),@inicio),convert(time,DATEADD(MILLISECOND,rand()*(@diferenciatiempo+1),'00:00:00')),1.4)
insert into checkin(lugar_id,usuario_id,comentario,fecha,hora,valoracion)
values(14,51,'sdsd',DATEADD(day,rand()*(@diferenciadias-1+1),@inicio),convert(time,DATEADD(MILLISECOND,rand()*(@diferenciatiempo+1),'00:00:00')),4.9)
insert into checkin(lugar_id,usuario_id,comentario,fecha,hora,valoracion)
values(1,11,'sdsd',DATEADD(day,rand()*(@diferenciadias-1+1),@inicio),convert(time,DATEADD(MILLISECOND,rand()*(@diferenciatiempo+1),'00:00:00')),0.8)
insert into checkin(lugar_id,usuario_id,comentario,fecha,hora,valoracion)
values(7,96,'sdsd',DATEADD(day,rand()*(@diferenciadias-1+1),@inicio),convert(time,DATEADD(MILLISECOND,rand()*(@diferenciatiempo+1),'00:00:00')),0.8)
insert into checkin(lugar_id,usuario_id,comentario,fecha,hora,valoracion)
values(15,22,'sdsd',DATEADD(day,rand()*(@diferenciadias-1+1),@inicio),convert(time,DATEADD(MILLISECOND,rand()*(@diferenciatiempo+1),'00:00:00')),1)
insert into checkin(lugar_id,usuario_id,comentario,fecha,hora,valoracion)
values(9,92,'sdsd',DATEADD(day,rand()*(@diferenciadias-1+1),@inicio),convert(time,DATEADD(MILLISECOND,rand()*(@diferenciatiempo+1),'00:00:00')),0.7)
insert into checkin(lugar_id,usuario_id,comentario,fecha,hora,valoracion)
values(1,103,'sdsd',DATEADD(day,rand()*(@diferenciadias-1+1),@inicio),convert(time,DATEADD(MILLISECOND,rand()*(@diferenciatiempo+1),'00:00:00')),4.4)
insert into checkin(lugar_id,usuario_id,comentario,fecha,hora,valoracion)
values(3,38,'sdsd',DATEADD(day,rand()*(@diferenciadias-1+1),@inicio),convert(time,DATEADD(MILLISECOND,rand()*(@diferenciatiempo+1),'00:00:00')),0.8)
insert into checkin(lugar_id,usuario_id,comentario,fecha,hora,valoracion)
values(12,15,'sdsd',DATEADD(day,rand()*(@diferenciadias-1+1),@inicio),convert(time,DATEADD(MILLISECOND,rand()*(@diferenciatiempo+1),'00:00:00')),1)
insert into checkin(lugar_id,usuario_id,comentario,fecha,hora,valoracion)
values(2,56,'sdsd',DATEADD(day,rand()*(@diferenciadias-1+1),@inicio),convert(time,DATEADD(MILLISECOND,rand()*(@diferenciatiempo+1),'00:00:00')),4.8)
insert into checkin(lugar_id,usuario_id,comentario,fecha,hora,valoracion)
values(2,4,'sdsd',DATEADD(day,rand()*(@diferenciadias-1+1),@inicio),convert(time,DATEADD(MILLISECOND,rand()*(@diferenciatiempo+1),'00:00:00')),2.7)
insert into checkin(lugar_id,usuario_id,comentario,fecha,hora,valoracion)
values(12,113,'sdsd',DATEADD(day,rand()*(@diferenciadias-1+1),@inicio),convert(time,DATEADD(MILLISECOND,rand()*(@diferenciatiempo+1),'00:00:00')),3.6)
insert into checkin(lugar_id,usuario_id,comentario,fecha,hora,valoracion)
values(8,56,'sdsd',DATEADD(day,rand()*(@diferenciadias-1+1),@inicio),convert(time,DATEADD(MILLISECOND,rand()*(@diferenciatiempo+1),'00:00:00')),0.2)
insert into checkin(lugar_id,usuario_id,comentario,fecha,hora,valoracion)
values(13,88,'sdsd',DATEADD(day,rand()*(@diferenciadias-1+1),@inicio),convert(time,DATEADD(MILLISECOND,rand()*(@diferenciatiempo+1),'00:00:00')),2.4)
insert into checkin(lugar_id,usuario_id,comentario,fecha,hora,valoracion)
values(6,100,'sdsd',DATEADD(day,rand()*(@diferenciadias-1+1),@inicio),convert(time,DATEADD(MILLISECOND,rand()*(@diferenciatiempo+1),'00:00:00')),3.7)
insert into checkin(lugar_id,usuario_id,comentario,fecha,hora,valoracion)
values(12,105,'sdsd',DATEADD(day,rand()*(@diferenciadias-1+1),@inicio),convert(time,DATEADD(MILLISECOND,rand()*(@diferenciatiempo+1),'00:00:00')),1.6)
insert into checkin(lugar_id,usuario_id,comentario,fecha,hora,valoracion)
values(8,67,'sdsd',DATEADD(day,rand()*(@diferenciadias-1+1),@inicio),convert(time,DATEADD(MILLISECOND,rand()*(@diferenciatiempo+1),'00:00:00')),0.3)
insert into checkin(lugar_id,usuario_id,comentario,fecha,hora,valoracion)
values(13,59,'sdsd',DATEADD(day,rand()*(@diferenciadias-1+1),@inicio),convert(time,DATEADD(MILLISECOND,rand()*(@diferenciatiempo+1),'00:00:00')),2.2)


---Solicitud
select*from Solicitud
insert into Solicitud(fecha,id_recibe,id_envio,estado)
values(DATEADD(day,rand()*(@diferenciadias-1+1),@inicio),34,13,'Aceptado')
insert into Solicitud(fecha,id_recibe,id_envio,estado)
values(DATEADD(day,rand()*(@diferenciadias-1+1),@inicio),110,10,'Aceptado')
insert into Solicitud(fecha,id_recibe,id_envio,estado)
values(DATEADD(day,rand()*(@diferenciadias-1+1),@inicio),33,1,'Rechazado')
insert into Solicitud(fecha,id_recibe,id_envio,estado)
values(DATEADD(day,rand()*(@diferenciadias-1+1),@inicio),4,6,'Aceptado')
insert into Solicitud(fecha,id_recibe,id_envio,estado)
values(DATEADD(day,rand()*(@diferenciadias-1+1),@inicio),12,15,'Aceptado')
insert into Solicitud(fecha,id_recibe,id_envio,estado)
values(DATEADD(day,rand()*(@diferenciadias-1+1),@inicio),26,8,'Rechazado')
insert into Solicitud(fecha,id_recibe,id_envio,estado)
values(DATEADD(day,rand()*(@diferenciadias-1+1),@inicio),71,4,'En espera')
insert into Solicitud(fecha,id_recibe,id_envio,estado)
values(DATEADD(day,rand()*(@diferenciadias-1+1),@inicio),38,2,'Aceptado')
insert into Solicitud(fecha,id_recibe,id_envio,estado)
values(DATEADD(day,rand()*(@diferenciadias-1+1),@inicio),39,6,'Aceptado')
insert into Solicitud(fecha,id_recibe,id_envio,estado)
values(DATEADD(day,rand()*(@diferenciadias-1+1),@inicio),104,6,'En espera')
insert into Solicitud(fecha,id_recibe,id_envio,estado)
values(DATEADD(day,rand()*(@diferenciadias-1+1),@inicio),64,14,'Aceptado')
insert into Solicitud(fecha,id_recibe,id_envio,estado)
values(DATEADD(day,rand()*(@diferenciadias-1+1),@inicio),45,15,'Aceptado')
insert into Solicitud(fecha,id_recibe,id_envio,estado)
values(DATEADD(day,rand()*(@diferenciadias-1+1),@inicio),66,11,'Rechazado')
insert into Solicitud(fecha,id_recibe,id_envio,estado)
values(DATEADD(day,rand()*(@diferenciadias-1+1),@inicio),58,10,'Rechazado')
insert into Solicitud(fecha,id_recibe,id_envio,estado)
values(DATEADD(day,rand()*(@diferenciadias-1+1),@inicio),89,12,'En espera')
insert into Solicitud(fecha,id_recibe,id_envio,estado)
values(DATEADD(day,rand()*(@diferenciadias-1+1),@inicio),111,14,'En espera')
insert into Solicitud(fecha,id_recibe,id_envio,estado)
values(DATEADD(day,rand()*(@diferenciadias-1+1),@inicio),92,7,'Aceptado')
insert into Solicitud(fecha,id_recibe,id_envio,estado)
values(DATEADD(day,rand()*(@diferenciadias-1+1),@inicio),83,9,'Rechazado')
insert into Solicitud(fecha,id_recibe,id_envio,estado)
values(DATEADD(day,rand()*(@diferenciadias-1+1),@inicio),114,1,'Rechazado')
insert into Solicitud(fecha,id_recibe,id_envio,estado)
values(DATEADD(day,rand()*(@diferenciadias-1+1),@inicio),111,9,'Rechazado')
insert into Solicitud(fecha,id_recibe,id_envio,estado)
values(DATEADD(day,rand()*(@diferenciadias-1+1),@inicio),56,6,'Rechazado')
insert into Solicitud(fecha,id_recibe,id_envio,estado)
values(DATEADD(day,rand()*(@diferenciadias-1+1),@inicio),75,8,'Rechazado')
insert into Solicitud(fecha,id_recibe,id_envio,estado)
values(DATEADD(day,rand()*(@diferenciadias-1+1),@inicio),98,7,'Rechazado')
insert into Solicitud(fecha,id_recibe,id_envio,estado)
values(DATEADD(day,rand()*(@diferenciadias-1+1),@inicio),99,14,'Rechazado')
insert into Solicitud(fecha,id_recibe,id_envio,estado)
values(DATEADD(day,rand()*(@diferenciadias-1+1),@inicio),37,8,'Aceptado')
insert into Solicitud(fecha,id_recibe,id_envio,estado)
values(DATEADD(day,rand()*(@diferenciadias-1+1),@inicio),44,6,'Rechazado')
insert into Solicitud(fecha,id_recibe,id_envio,estado)
values(DATEADD(day,rand()*(@diferenciadias-1+1),@inicio),21,1,'En espera')
insert into Solicitud(fecha,id_recibe,id_envio,estado)
values(DATEADD(day,rand()*(@diferenciadias-1+1),@inicio),15,14,'Aceptado')
insert into Solicitud(fecha,id_recibe,id_envio,estado)
values(DATEADD(day,rand()*(@diferenciadias-1+1),@inicio),16,5,'Rechazado')
insert into Solicitud(fecha,id_recibe,id_envio,estado)
values(DATEADD(day,rand()*(@diferenciadias-1+1),@inicio),54,3,'Rechazado')
insert into Solicitud(fecha,id_recibe,id_envio,estado)
values(DATEADD(day,rand()*(@diferenciadias-1+1),@inicio),95,5,'Aceptado')
insert into Solicitud(fecha,id_recibe,id_envio,estado)
values(DATEADD(day,rand()*(@diferenciadias-1+1),@inicio),24,11,'En espera')
insert into Solicitud(fecha,id_recibe,id_envio,estado)
values(DATEADD(day,rand()*(@diferenciadias-1+1),@inicio),82,14,'Aceptado')
insert into Solicitud(fecha,id_recibe,id_envio,estado)
values(DATEADD(day,rand()*(@diferenciadias-1+1),@inicio),30,2,'Aceptado')
insert into Solicitud(fecha,id_recibe,id_envio,estado)
values(DATEADD(day,rand()*(@diferenciadias-1+1),@inicio),100,8,'Aceptado')
insert into Solicitud(fecha,id_recibe,id_envio,estado)
values(DATEADD(day,rand()*(@diferenciadias-1+1),@inicio),88,11,'Rechazado')
insert into Solicitud(fecha,id_recibe,id_envio,estado)
values(DATEADD(day,rand()*(@diferenciadias-1+1),@inicio),55,11,'En espera')
insert into Solicitud(fecha,id_recibe,id_envio,estado)
values(DATEADD(day,rand()*(@diferenciadias-1+1),@inicio),19,9,'En espera')
insert into Solicitud(fecha,id_recibe,id_envio,estado)
values(DATEADD(day,rand()*(@diferenciadias-1+1),@inicio),22,14,'Rechazado')
insert into Solicitud(fecha,id_recibe,id_envio,estado)
values(DATEADD(day,rand()*(@diferenciadias-1+1),@inicio),65,1,'Rechazado')
insert into Solicitud(fecha,id_recibe,id_envio,estado)
values(DATEADD(day,rand()*(@diferenciadias-1+1),@inicio),63,12,'Aceptado')
insert into Solicitud(fecha,id_recibe,id_envio,estado)
values(DATEADD(day,rand()*(@diferenciadias-1+1),@inicio),59,14,'En espera')
insert into Solicitud(fecha,id_recibe,id_envio,estado)
values(DATEADD(day,rand()*(@diferenciadias-1+1),@inicio),3,10,'Rechazado')
insert into Solicitud(fecha,id_recibe,id_envio,estado)
values(DATEADD(day,rand()*(@diferenciadias-1+1),@inicio),86,4,'En espera')
insert into Solicitud(fecha,id_recibe,id_envio,estado)
values(DATEADD(day,rand()*(@diferenciadias-1+1),@inicio),109,14,'En espera')
insert into Solicitud(fecha,id_recibe,id_envio,estado)
values(DATEADD(day,rand()*(@diferenciadias-1+1),@inicio),90,8,'En espera')
insert into Solicitud(fecha,id_recibe,id_envio,estado)
values(DATEADD(day,rand()*(@diferenciadias-1+1),@inicio),17,13,'En espera')
insert into Solicitud(fecha,id_recibe,id_envio,estado)
values(DATEADD(day,rand()*(@diferenciadias-1+1),@inicio),41,9,'En espera')
insert into Solicitud(fecha,id_recibe,id_envio,estado)
values(DATEADD(day,rand()*(@diferenciadias-1+1),@inicio),65,13,'En espera')
insert into Solicitud(fecha,id_recibe,id_envio,estado)
values(DATEADD(day,rand()*(@diferenciadias-1+1),@inicio),38,5,'Rechazado')
insert into Solicitud(fecha,id_recibe,id_envio,estado)
values(DATEADD(day,rand()*(@diferenciadias-1+1),@inicio),72,4,'En espera')
insert into Solicitud(fecha,id_recibe,id_envio,estado)
values(DATEADD(day,rand()*(@diferenciadias-1+1),@inicio),17,6,'Aceptado')
insert into Solicitud(fecha,id_recibe,id_envio,estado)
values(DATEADD(day,rand()*(@diferenciadias-1+1),@inicio),23,8,'En espera')
insert into Solicitud(fecha,id_recibe,id_envio,estado)
values(DATEADD(day,rand()*(@diferenciadias-1+1),@inicio),31,13,'Aceptado')
insert into Solicitud(fecha,id_recibe,id_envio,estado)
values(DATEADD(day,rand()*(@diferenciadias-1+1),@inicio),9,7,'En espera')
insert into Solicitud(fecha,id_recibe,id_envio,estado)
values(DATEADD(day,rand()*(@diferenciadias-1+1),@inicio),98,9,'Aceptado')
insert into Solicitud(fecha,id_recibe,id_envio,estado)
values(DATEADD(day,rand()*(@diferenciadias-1+1),@inicio),1,4,'En espera')
insert into Solicitud(fecha,id_recibe,id_envio,estado)
values(DATEADD(day,rand()*(@diferenciadias-1+1),@inicio),95,32,'En espera')
insert into Solicitud(fecha,id_recibe,id_envio,estado)
values(DATEADD(day,rand()*(@diferenciadias-1+1),@inicio),43,4,'Rechazado')
insert into Solicitud(fecha,id_recibe,id_envio,estado)
values(DATEADD(day,rand()*(@diferenciadias-1+1),@inicio),68,12,'Aceptado')
insert into Solicitud(fecha,id_recibe,id_envio,estado)
values(DATEADD(day,rand()*(@diferenciadias-1+1),@inicio),1,9,'En espera')
insert into Solicitud(fecha,id_recibe,id_envio,estado)
values(DATEADD(day,rand()*(@diferenciadias-1+1),@inicio),57,15,'Aceptado')
insert into Solicitud(fecha,id_recibe,id_envio,estado)
values(DATEADD(day,rand()*(@diferenciadias-1+1),@inicio),38,6,'Aceptado')
insert into Solicitud(fecha,id_recibe,id_envio,estado)
values(DATEADD(day,rand()*(@diferenciadias-1+1),@inicio),43,3,'Rechazado')
insert into Solicitud(fecha,id_recibe,id_envio,estado)
values(DATEADD(day,rand()*(@diferenciadias-1+1),@inicio),16,14,'En espera')
insert into Solicitud(fecha,id_recibe,id_envio,estado)
values(DATEADD(day,rand()*(@diferenciadias-1+1),@inicio),100,6,'En espera')
insert into Solicitud(fecha,id_recibe,id_envio,estado)
values(DATEADD(day,rand()*(@diferenciadias-1+1),@inicio),93,13,'Rechazado')
insert into Solicitud(fecha,id_recibe,id_envio,estado)
values(DATEADD(day,rand()*(@diferenciadias-1+1),@inicio),73,8,'Rechazado')
insert into Solicitud(fecha,id_recibe,id_envio,estado)
values(DATEADD(day,rand()*(@diferenciadias-1+1),@inicio),2,9,'Rechazado')
insert into Solicitud(fecha,id_recibe,id_envio,estado)
values(DATEADD(day,rand()*(@diferenciadias-1+1),@inicio),34,2,'Aceptado')
insert into Solicitud(fecha,id_recibe,id_envio,estado)
values(DATEADD(day,rand()*(@diferenciadias-1+1),@inicio),38,14,'Aceptado')
insert into Solicitud(fecha,id_recibe,id_envio,estado)
values(DATEADD(day,rand()*(@diferenciadias-1+1),@inicio),100,1,'Aceptado')
insert into Solicitud(fecha,id_recibe,id_envio,estado)
values(DATEADD(day,rand()*(@diferenciadias-1+1),@inicio),79,1,'Rechazado')
insert into Solicitud(fecha,id_recibe,id_envio,estado)
values(DATEADD(day,rand()*(@diferenciadias-1+1),@inicio),91,2,'Aceptado')
insert into Solicitud(fecha,id_recibe,id_envio,estado)
values(DATEADD(day,rand()*(@diferenciadias-1+1),@inicio),38,11,'En espera')
insert into Solicitud(fecha,id_recibe,id_envio,estado)
values(DATEADD(day,rand()*(@diferenciadias-1+1),@inicio),6,1,'Rechazado')
insert into Solicitud(fecha,id_recibe,id_envio,estado)
values(DATEADD(day,rand()*(@diferenciadias-1+1),@inicio),85,8,'Aceptado')
insert into Solicitud(fecha,id_recibe,id_envio,estado)
values(DATEADD(day,rand()*(@diferenciadias-1+1),@inicio),19,11,'Aceptado')
insert into Solicitud(fecha,id_recibe,id_envio,estado)
values(DATEADD(day,rand()*(@diferenciadias-1+1),@inicio),102,8,'Aceptado')
insert into Solicitud(fecha,id_recibe,id_envio,estado)
values(DATEADD(day,rand()*(@diferenciadias-1+1),@inicio),86,2,'En espera')
insert into Solicitud(fecha,id_recibe,id_envio,estado)
values(DATEADD(day,rand()*(@diferenciadias-1+1),@inicio),31,9,'En espera')
insert into Solicitud(fecha,id_recibe,id_envio,estado)
values(DATEADD(day,rand()*(@diferenciadias-1+1),@inicio),18,4,'En espera')
insert into Solicitud(fecha,id_recibe,id_envio,estado)
values(DATEADD(day,rand()*(@diferenciadias-1+1),@inicio),75,9,'Rechazado')
insert into Solicitud(fecha,id_recibe,id_envio,estado)
values(DATEADD(day,rand()*(@diferenciadias-1+1),@inicio),2,14,'Aceptado')
insert into Solicitud(fecha,id_recibe,id_envio,estado)
values(DATEADD(day,rand()*(@diferenciadias-1+1),@inicio),39,11,'Rechazado')
insert into Solicitud(fecha,id_recibe,id_envio,estado)
values(DATEADD(day,rand()*(@diferenciadias-1+1),@inicio),89,9,'Aceptado')
insert into Solicitud(fecha,id_recibe,id_envio,estado)
values(DATEADD(day,rand()*(@diferenciadias-1+1),@inicio),49,7,'Aceptado')
insert into Solicitud(fecha,id_recibe,id_envio,estado)
values(DATEADD(day,rand()*(@diferenciadias-1+1),@inicio),19,10,'Aceptado')
insert into Solicitud(fecha,id_recibe,id_envio,estado)
values(DATEADD(day,rand()*(@diferenciadias-1+1),@inicio),22,9,'Rechazado')
insert into Solicitud(fecha,id_recibe,id_envio,estado)
values(DATEADD(day,rand()*(@diferenciadias-1+1),@inicio),9,2,'Rechazado')
insert into Solicitud(fecha,id_recibe,id_envio,estado)
values(DATEADD(day,rand()*(@diferenciadias-1+1),@inicio),93,15,'Aceptado')
insert into Solicitud(fecha,id_recibe,id_envio,estado)
values(DATEADD(day,rand()*(@diferenciadias-1+1),@inicio),49,4,'Rechazado')
insert into Solicitud(fecha,id_recibe,id_envio,estado)
values(DATEADD(day,rand()*(@diferenciadias-1+1),@inicio),60,10,'Rechazado')
insert into Solicitud(fecha,id_recibe,id_envio,estado)
values(DATEADD(day,rand()*(@diferenciadias-1+1),@inicio),47,8,'Rechazado')
insert into Solicitud(fecha,id_recibe,id_envio,estado)
values(DATEADD(day,rand()*(@diferenciadias-1+1),@inicio),87,5,'Aceptado')
insert into Solicitud(fecha,id_recibe,id_envio,estado)
values(DATEADD(day,rand()*(@diferenciadias-1+1),@inicio),64,13,'Rechazado')
insert into Solicitud(fecha,id_recibe,id_envio,estado)
values(DATEADD(day,rand()*(@diferenciadias-1+1),@inicio),36,5,'Rechazado')
insert into Solicitud(fecha,id_recibe,id_envio,estado)
values(DATEADD(day,rand()*(@diferenciadias-1+1),@inicio),114,2,'Aceptado')
insert into Solicitud(fecha,id_recibe,id_envio,estado)
values(DATEADD(day,rand()*(@diferenciadias-1+1),@inicio),32,7,'En espera')
insert into Solicitud(fecha,id_recibe,id_envio,estado)
values(DATEADD(day,rand()*(@diferenciadias-1+1),@inicio),77,1,'En espera')

---Insignia
select*from Insignia
insert into Insignia(tipoinsignia,descripcion)
values('Fotogénico','Hacer checkin en 3 lugares diferentes con cabina de fotos')
insert into Insignia(tipoinsignia,descripcion)
values('La Voz','Hacer 3 check-ins en un mes desde lugares con la categoría "Karaoke Bar" (se puede repetir)')
insert into Insignia(tipoinsignia,descripcion)
values('Melómano','Hacer 5 check-in en lugares de la categoría "Tienda de música"')
insert into Insignia(tipoinsignia,descripcion)
values('Cinéflo','Hacer 15 check-in en cines')
insert into Insignia(tipoinsignia,descripcion)
values('Trabajador','Hacer 20 check-in en lugares de la categoría "Oficinas"')
insert into Insignia(tipoinsignia,descripcion)
values('Godinez','Hacer 30 check-in en lugares con la categoria "Oficina" durante un mes')
insert into Insignia(tipoinsignia,descripcion)
values('Catador de comida','Hacer check-ins en 10 restaurantes diferentes')
insert into Insignia(tipoinsignia,descripcion)
values('Navegante','Hacer check-in desde 3 lugares diferentes con la etiqueta "canoa"')
insert into Insignia(tipoinsignia,descripcion)
values('Borracho','Hacer check-in desde 5 lugares diferentes de categoria "Bar" dentro de una misma semana')
insert into Insignia(tipoinsignia,descripcion)
values('Fiestero','Hacer check-in desde 3 lugares diferentes de categoria "Club Nocturno" dentro de una misma noche')
insert into Insignia(tipoinsignia,descripcion)
values('Carnivoro','Hacer check-in desde 5 lugares diferentes de categoria "Carniceria" durante un mes')

---Interes
select*from Interes order by id
insert into Interes(nombre)
values('Videojuegos')
insert into Interes(nombre)
values('Programación')
insert into Interes(nombre)
values('Java')
insert into Interes(nombre)
values('SQL')
insert into Interes(nombre)
values('Music')
insert into Interes(nombre)
values('Chicas')
insert into Interes(nombre)
values('Weed')
insert into Interes(nombre)
values('Travel')
insert into Interes(nombre)
values('Party')
insert into Interes(nombre)
values('Libros')
insert into Interes(nombre)
values('Cine')
insert into Interes(nombre)
values('Food')
insert into Interes(nombre)
values('México')
insert into Interes(nombre)
values('Rock & Roll')
insert into Interes(nombre)
values('Beer')
insert into Interes(nombre)
values('Fotografía')
insert into Interes(nombre)
values('PC')
insert into Interes(nombre)
values('Dreamer')
insert into Interes(nombre)
values('Anime')
insert into Interes(nombre)
values('Cartoon')
insert into Interes(nombre)
values('Corridos')
insert into Interes(nombre)
values('Smoke')
insert into Interes(nombre)
values('Frutas')
insert into Interes(nombre)
values('Summer')
insert into Interes(nombre)
values('Youtube')
insert into Interes(nombre)
values('Facebook')
insert into Interes(nombre)
values('Twitter')
insert into Interes(nombre)
values('Ingeniería')
insert into Interes(nombre)
values('Sinaloa')
insert into Interes(nombre)
values('Art')
insert into Interes(nombre)
values('Drawing')
insert into Interes(nombre)
values('Vodka')
insert into Interes(nombre)
values('Marvel')

---Interes-Usuario
select*from Intereses_Usuario
insert into Intereses_Usuario(id_usuario,id_interes)
values(5,3)
insert into Intereses_Usuario(id_usuario,id_interes)
values(60,30)
insert into Intereses_Usuario(id_usuario,id_interes)
values(86,10)
insert into Intereses_Usuario(id_usuario,id_interes)
values(104,30)
insert into Intereses_Usuario(id_usuario,id_interes)
values(50,8)
insert into Intereses_Usuario(id_usuario,id_interes)
values(69,11)
insert into Intereses_Usuario(id_usuario,id_interes)
values(98,26)
insert into Intereses_Usuario(id_usuario,id_interes)
values(110,11)
insert into Intereses_Usuario(id_usuario,id_interes)
values(100,27)
insert into Intereses_Usuario(id_usuario,id_interes)
values(46,31)
insert into Intereses_Usuario(id_usuario,id_interes)
values(99,33)
insert into Intereses_Usuario(id_usuario,id_interes)
values(50,4)
insert into Intereses_Usuario(id_usuario,id_interes)
values(70,10)
insert into Intereses_Usuario(id_usuario,id_interes)
values(65,1)
insert into Intereses_Usuario(id_usuario,id_interes)
values(29,6)
insert into Intereses_Usuario(id_usuario,id_interes)
values(65,31)
insert into Intereses_Usuario(id_usuario,id_interes)
values(13,27)
insert into Intereses_Usuario(id_usuario,id_interes)
values(49,7)
insert into Intereses_Usuario(id_usuario,id_interes)
values(83,7)
insert into Intereses_Usuario(id_usuario,id_interes)
values(52,31)
insert into Intereses_Usuario(id_usuario,id_interes)
values(58,12)
insert into Intereses_Usuario(id_usuario,id_interes)
values(54,24)
insert into Intereses_Usuario(id_usuario,id_interes)
values(81,1)
insert into Intereses_Usuario(id_usuario,id_interes)
values(64,29)
insert into Intereses_Usuario(id_usuario,id_interes)
values(34,27)
insert into Intereses_Usuario(id_usuario,id_interes)
values(7,16)
insert into Intereses_Usuario(id_usuario,id_interes)
values(57,16)
insert into Intereses_Usuario(id_usuario,id_interes)
values(51,6)
insert into Intereses_Usuario(id_usuario,id_interes)
values(20,23)
insert into Intereses_Usuario(id_usuario,id_interes)
values(65,19)
insert into Intereses_Usuario(id_usuario,id_interes)
values(50,13)
insert into Intereses_Usuario(id_usuario,id_interes)
values(24,9)
insert into Intereses_Usuario(id_usuario,id_interes)
values(21,30)
insert into Intereses_Usuario(id_usuario,id_interes)
values(10,8)
insert into Intereses_Usuario(id_usuario,id_interes)
values(97,5)
insert into Intereses_Usuario(id_usuario,id_interes)
values(64,33)
insert into Intereses_Usuario(id_usuario,id_interes)
values(3,16)
insert into Intereses_Usuario(id_usuario,id_interes)
values(52,8)
insert into Intereses_Usuario(id_usuario,id_interes)
values(72,6)
insert into Intereses_Usuario(id_usuario,id_interes)
values(23,16)
insert into Intereses_Usuario(id_usuario,id_interes)
values(53,20)
insert into Intereses_Usuario(id_usuario,id_interes)
values(102,10)
insert into Intereses_Usuario(id_usuario,id_interes)
values(64,19)
insert into Intereses_Usuario(id_usuario,id_interes)
values(68,1)
insert into Intereses_Usuario(id_usuario,id_interes)
values(90,13)
insert into Intereses_Usuario(id_usuario,id_interes)
values(5,1)
insert into Intereses_Usuario(id_usuario,id_interes)
values(105,20)
insert into Intereses_Usuario(id_usuario,id_interes)
values(13,1)
insert into Intereses_Usuario(id_usuario,id_interes)
values(80,23)
insert into Intereses_Usuario(id_usuario,id_interes)
values(106,2)
insert into Intereses_Usuario(id_usuario,id_interes)
values(28,7)
insert into Intereses_Usuario(id_usuario,id_interes)
values(35,21)
insert into Intereses_Usuario(id_usuario,id_interes)
values(25,5)
insert into Intereses_Usuario(id_usuario,id_interes)
values(20,10)
insert into Intereses_Usuario(id_usuario,id_interes)
values(113,19)
insert into Intereses_Usuario(id_usuario,id_interes)
values(26,25)
insert into Intereses_Usuario(id_usuario,id_interes)
values(111,9)
insert into Intereses_Usuario(id_usuario,id_interes)
values(105,26)
insert into Intereses_Usuario(id_usuario,id_interes)
values(23,17)
insert into Intereses_Usuario(id_usuario,id_interes)
values(64,23)
insert into Intereses_Usuario(id_usuario,id_interes)
values(61,27)
insert into Intereses_Usuario(id_usuario,id_interes)
values(69,31)
insert into Intereses_Usuario(id_usuario,id_interes)
values(26,15)
insert into Intereses_Usuario(id_usuario,id_interes)
values(4,13)
insert into Intereses_Usuario(id_usuario,id_interes)
values(1,2)

---Logro
select*from Logro
insert into Logro(id_insignia,lugar_id,id_usuario,fecha,hora)
values(5,11,7,DATEADD(day,rand()*(@diferenciadias-1+1),@inicio),convert(time,DATEADD(MILLISECOND,rand()*(@diferenciatiempo+1),'00:00:00')))
insert into Logro(id_insignia,lugar_id,id_usuario,fecha,hora)
values(8,5,91,DATEADD(day,rand()*(@diferenciadias-1+1),@inicio),convert(time,DATEADD(MILLISECOND,rand()*(@diferenciatiempo+1),'00:00:00')))
insert into Logro(id_insignia,lugar_id,id_usuario,fecha,hora)
values(6,9,88,DATEADD(day,rand()*(@diferenciadias-1+1),@inicio),convert(time,DATEADD(MILLISECOND,rand()*(@diferenciatiempo+1),'00:00:00')))
insert into Logro(id_insignia,lugar_id,id_usuario,fecha,hora)
values(8,10,12,DATEADD(day,rand()*(@diferenciadias-1+1),@inicio),convert(time,DATEADD(MILLISECOND,rand()*(@diferenciatiempo+1),'00:00:00')))
insert into Logro(id_insignia,lugar_id,id_usuario,fecha,hora)
values(9,11,47,DATEADD(day,rand()*(@diferenciadias-1+1),@inicio),convert(time,DATEADD(MILLISECOND,rand()*(@diferenciatiempo+1),'00:00:00')))
insert into Logro(id_insignia,lugar_id,id_usuario,fecha,hora)
values(5,2,80,DATEADD(day,rand()*(@diferenciadias-1+1),@inicio),convert(time,DATEADD(MILLISECOND,rand()*(@diferenciatiempo+1),'00:00:00')))
insert into Logro(id_insignia,lugar_id,id_usuario,fecha,hora)
values(2,2,80,DATEADD(day,rand()*(@diferenciadias-1+1),@inicio),convert(time,DATEADD(MILLISECOND,rand()*(@diferenciatiempo+1),'00:00:00')))
insert into Logro(id_insignia,lugar_id,id_usuario,fecha,hora)
values(2,3,103,DATEADD(day,rand()*(@diferenciadias-1+1),@inicio),convert(time,DATEADD(MILLISECOND,rand()*(@diferenciatiempo+1),'00:00:00')))
insert into Logro(id_insignia,lugar_id,id_usuario,fecha,hora)
values(6,11,1,DATEADD(day,rand()*(@diferenciadias-1+1),@inicio),convert(time,DATEADD(MILLISECOND,rand()*(@diferenciatiempo+1),'00:00:00')))
insert into Logro(id_insignia,lugar_id,id_usuario,fecha,hora)
values(6,12,43,DATEADD(day,rand()*(@diferenciadias-1+1),@inicio),convert(time,DATEADD(MILLISECOND,rand()*(@diferenciatiempo+1),'00:00:00')))
insert into Logro(id_insignia,lugar_id,id_usuario,fecha,hora)
values(10,15,103,DATEADD(day,rand()*(@diferenciadias-1+1),@inicio),convert(time,DATEADD(MILLISECOND,rand()*(@diferenciatiempo+1),'00:00:00')))
insert into Logro(id_insignia,lugar_id,id_usuario,fecha,hora)
values(5,15,44,DATEADD(day,rand()*(@diferenciadias-1+1),@inicio),convert(time,DATEADD(MILLISECOND,rand()*(@diferenciatiempo+1),'00:00:00')))
insert into Logro(id_insignia,lugar_id,id_usuario,fecha,hora)
values(5,9,23,DATEADD(day,rand()*(@diferenciadias-1+1),@inicio),convert(time,DATEADD(MILLISECOND,rand()*(@diferenciatiempo+1),'00:00:00')))
insert into Logro(id_insignia,lugar_id,id_usuario,fecha,hora)
values(5,14,81,DATEADD(day,rand()*(@diferenciadias-1+1),@inicio),convert(time,DATEADD(MILLISECOND,rand()*(@diferenciatiempo+1),'00:00:00')))
insert into Logro(id_insignia,lugar_id,id_usuario,fecha,hora)
values(9,2,65,DATEADD(day,rand()*(@diferenciadias-1+1),@inicio),convert(time,DATEADD(MILLISECOND,rand()*(@diferenciatiempo+1),'00:00:00')))
insert into Logro(id_insignia,lugar_id,id_usuario,fecha,hora)
values(1,1,35,DATEADD(day,rand()*(@diferenciadias-1+1),@inicio),convert(time,DATEADD(MILLISECOND,rand()*(@diferenciatiempo+1),'00:00:00')))
insert into Logro(id_insignia,lugar_id,id_usuario,fecha,hora)
values(11,12,23,DATEADD(day,rand()*(@diferenciadias-1+1),@inicio),convert(time,DATEADD(MILLISECOND,rand()*(@diferenciatiempo+1),'00:00:00')))
insert into Logro(id_insignia,lugar_id,id_usuario,fecha,hora)
values(9,5,68,DATEADD(day,rand()*(@diferenciadias-1+1),@inicio),convert(time,DATEADD(MILLISECOND,rand()*(@diferenciatiempo+1),'00:00:00')))
insert into Logro(id_insignia,lugar_id,id_usuario,fecha,hora)
values(8,3,2,DATEADD(day,rand()*(@diferenciadias-1+1),@inicio),convert(time,DATEADD(MILLISECOND,rand()*(@diferenciatiempo+1),'00:00:00')))
insert into Logro(id_insignia,lugar_id,id_usuario,fecha,hora)
values(3,14,1,DATEADD(day,rand()*(@diferenciadias-1+1),@inicio),convert(time,DATEADD(MILLISECOND,rand()*(@diferenciatiempo+1),'00:00:00')))
insert into Logro(id_insignia,lugar_id,id_usuario,fecha,hora)
values(5,12,30,DATEADD(day,rand()*(@diferenciadias-1+1),@inicio),convert(time,DATEADD(MILLISECOND,rand()*(@diferenciatiempo+1),'00:00:00')))
insert into Logro(id_insignia,lugar_id,id_usuario,fecha,hora)
values(1,7,14,DATEADD(day,rand()*(@diferenciadias-1+1),@inicio),convert(time,DATEADD(MILLISECOND,rand()*(@diferenciatiempo+1),'00:00:00')))
insert into Logro(id_insignia,lugar_id,id_usuario,fecha,hora)
values(4,11,84,DATEADD(day,rand()*(@diferenciadias-1+1),@inicio),convert(time,DATEADD(MILLISECOND,rand()*(@diferenciatiempo+1),'00:00:00')))
insert into Logro(id_insignia,lugar_id,id_usuario,fecha,hora)
values(8,13,80,DATEADD(day,rand()*(@diferenciadias-1+1),@inicio),convert(time,DATEADD(MILLISECOND,rand()*(@diferenciatiempo+1),'00:00:00')))
insert into Logro(id_insignia,lugar_id,id_usuario,fecha,hora)
values(1,13,64,DATEADD(day,rand()*(@diferenciadias-1+1),@inicio),convert(time,DATEADD(MILLISECOND,rand()*(@diferenciatiempo+1),'00:00:00')))
insert into Logro(id_insignia,lugar_id,id_usuario,fecha,hora)
values(8,5,32,DATEADD(day,rand()*(@diferenciadias-1+1),@inicio),convert(time,DATEADD(MILLISECOND,rand()*(@diferenciatiempo+1),'00:00:00')))
insert into Logro(id_insignia,lugar_id,id_usuario,fecha,hora)
values(6,4,84,DATEADD(day,rand()*(@diferenciadias-1+1),@inicio),convert(time,DATEADD(MILLISECOND,rand()*(@diferenciatiempo+1),'00:00:00')))
insert into Logro(id_insignia,lugar_id,id_usuario,fecha,hora)
values(9,9,91,DATEADD(day,rand()*(@diferenciadias-1+1),@inicio),convert(time,DATEADD(MILLISECOND,rand()*(@diferenciatiempo+1),'00:00:00')))
insert into Logro(id_insignia,lugar_id,id_usuario,fecha,hora)
values(7,15,46,DATEADD(day,rand()*(@diferenciadias-1+1),@inicio),convert(time,DATEADD(MILLISECOND,rand()*(@diferenciatiempo+1),'00:00:00')))
insert into Logro(id_insignia,lugar_id,id_usuario,fecha,hora)
values(8,1,46,DATEADD(day,rand()*(@diferenciadias-1+1),@inicio),convert(time,DATEADD(MILLISECOND,rand()*(@diferenciatiempo+1),'00:00:00')))
insert into Logro(id_insignia,lugar_id,id_usuario,fecha,hora)
values(5,12,112,DATEADD(day,rand()*(@diferenciadias-1+1),@inicio),convert(time,DATEADD(MILLISECOND,rand()*(@diferenciatiempo+1),'00:00:00')))
insert into Logro(id_insignia,lugar_id,id_usuario,fecha,hora)
values(10,6,2,DATEADD(day,rand()*(@diferenciadias-1+1),@inicio),convert(time,DATEADD(MILLISECOND,rand()*(@diferenciatiempo+1),'00:00:00')))
insert into Logro(id_insignia,lugar_id,id_usuario,fecha,hora)
values(4,13,40,DATEADD(day,rand()*(@diferenciadias-1+1),@inicio),convert(time,DATEADD(MILLISECOND,rand()*(@diferenciatiempo+1),'00:00:00')))
insert into Logro(id_insignia,lugar_id,id_usuario,fecha,hora)
values(2,13,35,DATEADD(day,rand()*(@diferenciadias-1+1),@inicio),convert(time,DATEADD(MILLISECOND,rand()*(@diferenciatiempo+1),'00:00:00')))
insert into Logro(id_insignia,lugar_id,id_usuario,fecha,hora)
values(4,10,85,DATEADD(day,rand()*(@diferenciadias-1+1),@inicio),convert(time,DATEADD(MILLISECOND,rand()*(@diferenciatiempo+1),'00:00:00')))
insert into Logro(id_insignia,lugar_id,id_usuario,fecha,hora)
values(6,12,96,DATEADD(day,rand()*(@diferenciadias-1+1),@inicio),convert(time,DATEADD(MILLISECOND,rand()*(@diferenciatiempo+1),'00:00:00')))
insert into Logro(id_insignia,lugar_id,id_usuario,fecha,hora)
values(10,9,44,DATEADD(day,rand()*(@diferenciadias-1+1),@inicio),convert(time,DATEADD(MILLISECOND,rand()*(@diferenciatiempo+1),'00:00:00')))
insert into Logro(id_insignia,lugar_id,id_usuario,fecha,hora)
values(4,2,33,DATEADD(day,rand()*(@diferenciadias-1+1),@inicio),convert(time,DATEADD(MILLISECOND,rand()*(@diferenciatiempo+1),'00:00:00')))
insert into Logro(id_insignia,lugar_id,id_usuario,fecha,hora)
values(9,1,60,DATEADD(day,rand()*(@diferenciadias-1+1),@inicio),convert(time,DATEADD(MILLISECOND,rand()*(@diferenciatiempo+1),'00:00:00')))
insert into Logro(id_insignia,lugar_id,id_usuario,fecha,hora)
values(6,4,108,DATEADD(day,rand()*(@diferenciadias-1+1),@inicio),convert(time,DATEADD(MILLISECOND,rand()*(@diferenciatiempo+1),'00:00:00')))
insert into Logro(id_insignia,lugar_id,id_usuario,fecha,hora)
values(3,2,42,DATEADD(day,rand()*(@diferenciadias-1+1),@inicio),convert(time,DATEADD(MILLISECOND,rand()*(@diferenciatiempo+1),'00:00:00')))
insert into Logro(id_insignia,lugar_id,id_usuario,fecha,hora)
values(7,13,10,DATEADD(day,rand()*(@diferenciadias-1+1),@inicio),convert(time,DATEADD(MILLISECOND,rand()*(@diferenciatiempo+1),'00:00:00')))
insert into Logro(id_insignia,lugar_id,id_usuario,fecha,hora)
values(10,9,33,DATEADD(day,rand()*(@diferenciadias-1+1),@inicio),convert(time,DATEADD(MILLISECOND,rand()*(@diferenciatiempo+1),'00:00:00')))
insert into Logro(id_insignia,lugar_id,id_usuario,fecha,hora)
values(1,6,68,DATEADD(day,rand()*(@diferenciadias-1+1),@inicio),convert(time,DATEADD(MILLISECOND,rand()*(@diferenciatiempo+1),'00:00:00')))
insert into Logro(id_insignia,lugar_id,id_usuario,fecha,hora)
values(10,2,21,DATEADD(day,rand()*(@diferenciadias-1+1),@inicio),convert(time,DATEADD(MILLISECOND,rand()*(@diferenciatiempo+1),'00:00:00')))
insert into Logro(id_insignia,lugar_id,id_usuario,fecha,hora)
values(10,5,34,DATEADD(day,rand()*(@diferenciadias-1+1),@inicio),convert(time,DATEADD(MILLISECOND,rand()*(@diferenciatiempo+1),'00:00:00')))
insert into Logro(id_insignia,lugar_id,id_usuario,fecha,hora)
values(10,9,30,DATEADD(day,rand()*(@diferenciadias-1+1),@inicio),convert(time,DATEADD(MILLISECOND,rand()*(@diferenciatiempo+1),'00:00:00')))
insert into Logro(id_insignia,lugar_id,id_usuario,fecha,hora)
values(5,10,96,DATEADD(day,rand()*(@diferenciadias-1+1),@inicio),convert(time,DATEADD(MILLISECOND,rand()*(@diferenciatiempo+1),'00:00:00')))
insert into Logro(id_insignia,lugar_id,id_usuario,fecha,hora)
values(3,11,55,DATEADD(day,rand()*(@diferenciadias-1+1),@inicio),convert(time,DATEADD(MILLISECOND,rand()*(@diferenciatiempo+1),'00:00:00')))
insert into Logro(id_insignia,lugar_id,id_usuario,fecha,hora)
values(4,2,54,DATEADD(day,rand()*(@diferenciadias-1+1),@inicio),convert(time,DATEADD(MILLISECOND,rand()*(@diferenciatiempo+1),'00:00:00')))
insert into Logro(id_insignia,lugar_id,id_usuario,fecha,hora)
values(1,9,39,DATEADD(day,rand()*(@diferenciadias-1+1),@inicio),convert(time,DATEADD(MILLISECOND,rand()*(@diferenciatiempo+1),'00:00:00')))
insert into Logro(id_insignia,lugar_id,id_usuario,fecha,hora)
values(9,10,111,DATEADD(day,rand()*(@diferenciadias-1+1),@inicio),convert(time,DATEADD(MILLISECOND,rand()*(@diferenciatiempo+1),'00:00:00')))
insert into Logro(id_insignia,lugar_id,id_usuario,fecha,hora)
values(6,13,48,DATEADD(day,rand()*(@diferenciadias-1+1),@inicio),convert(time,DATEADD(MILLISECOND,rand()*(@diferenciatiempo+1),'00:00:00')))
insert into Logro(id_insignia,lugar_id,id_usuario,fecha,hora)
values(11,6,99,DATEADD(day,rand()*(@diferenciadias-1+1),@inicio),convert(time,DATEADD(MILLISECOND,rand()*(@diferenciatiempo+1),'00:00:00')))
insert into Logro(id_insignia,lugar_id,id_usuario,fecha,hora)
values(9,13,92,DATEADD(day,rand()*(@diferenciadias-1+1),@inicio),convert(time,DATEADD(MILLISECOND,rand()*(@diferenciatiempo+1),'00:00:00')))
insert into Logro(id_insignia,lugar_id,id_usuario,fecha,hora)
values(11,7,56,DATEADD(day,rand()*(@diferenciadias-1+1),@inicio),convert(time,DATEADD(MILLISECOND,rand()*(@diferenciatiempo+1),'00:00:00')))
insert into Logro(id_insignia,lugar_id,id_usuario,fecha,hora)
values(6,2,91,DATEADD(day,rand()*(@diferenciadias-1+1),@inicio),convert(time,DATEADD(MILLISECOND,rand()*(@diferenciatiempo+1),'00:00:00')))
insert into Logro(id_insignia,lugar_id,id_usuario,fecha,hora)
values(9,6,90,DATEADD(day,rand()*(@diferenciadias-1+1),@inicio),convert(time,DATEADD(MILLISECOND,rand()*(@diferenciatiempo+1),'00:00:00')))
insert into Logro(id_insignia,lugar_id,id_usuario,fecha,hora)
values(7,13,45,DATEADD(day,rand()*(@diferenciadias-1+1),@inicio),convert(time,DATEADD(MILLISECOND,rand()*(@diferenciatiempo+1),'00:00:00')))
insert into Logro(id_insignia,lugar_id,id_usuario,fecha,hora)
values(11,5,113,DATEADD(day,rand()*(@diferenciadias-1+1),@inicio),convert(time,DATEADD(MILLISECOND,rand()*(@diferenciatiempo+1),'00:00:00')))
insert into Logro(id_insignia,lugar_id,id_usuario,fecha,hora)
values(4,7,12,DATEADD(day,rand()*(@diferenciadias-1+1),@inicio),convert(time,DATEADD(MILLISECOND,rand()*(@diferenciatiempo+1),'00:00:00')))
insert into Logro(id_insignia,lugar_id,id_usuario,fecha,hora)
values(3,11,109,DATEADD(day,rand()*(@diferenciadias-1+1),@inicio),convert(time,DATEADD(MILLISECOND,rand()*(@diferenciatiempo+1),'00:00:00')))
insert into Logro(id_insignia,lugar_id,id_usuario,fecha,hora)
values(10,12,63,DATEADD(day,rand()*(@diferenciadias-1+1),@inicio),convert(time,DATEADD(MILLISECOND,rand()*(@diferenciatiempo+1),'00:00:00')))
insert into Logro(id_insignia,lugar_id,id_usuario,fecha,hora)
values(7,14,81,DATEADD(day,rand()*(@diferenciadias-1+1),@inicio),convert(time,DATEADD(MILLISECOND,rand()*(@diferenciatiempo+1),'00:00:00')))
insert into Logro(id_insignia,lugar_id,id_usuario,fecha,hora)
values(7,9,21,DATEADD(day,rand()*(@diferenciadias-1+1),@inicio),convert(time,DATEADD(MILLISECOND,rand()*(@diferenciatiempo+1),'00:00:00')))
insert into Logro(id_insignia,lugar_id,id_usuario,fecha,hora)
values(8,6,111,DATEADD(day,rand()*(@diferenciadias-1+1),@inicio),convert(time,DATEADD(MILLISECOND,rand()*(@diferenciatiempo+1),'00:00:00')))
insert into Logro(id_insignia,lugar_id,id_usuario,fecha,hora)
values(6,9,9,DATEADD(day,rand()*(@diferenciadias-1+1),@inicio),convert(time,DATEADD(MILLISECOND,rand()*(@diferenciatiempo+1),'00:00:00')))
insert into Logro(id_insignia,lugar_id,id_usuario,fecha,hora)
values(7,1,52,DATEADD(day,rand()*(@diferenciadias-1+1),@inicio),convert(time,DATEADD(MILLISECOND,rand()*(@diferenciatiempo+1),'00:00:00')))
insert into Logro(id_insignia,lugar_id,id_usuario,fecha,hora)
values(8,9,93,DATEADD(day,rand()*(@diferenciadias-1+1),@inicio),convert(time,DATEADD(MILLISECOND,rand()*(@diferenciatiempo+1),'00:00:00')))
insert into Logro(id_insignia,lugar_id,id_usuario,fecha,hora)
values(11,10,25,DATEADD(day,rand()*(@diferenciadias-1+1),@inicio),convert(time,DATEADD(MILLISECOND,rand()*(@diferenciatiempo+1),'00:00:00')))
insert into Logro(id_insignia,lugar_id,id_usuario,fecha,hora)
values(2,10,61,DATEADD(day,rand()*(@diferenciadias-1+1),@inicio),convert(time,DATEADD(MILLISECOND,rand()*(@diferenciatiempo+1),'00:00:00')))
insert into Logro(id_insignia,lugar_id,id_usuario,fecha,hora)
values(4,6,75,DATEADD(day,rand()*(@diferenciadias-1+1),@inicio),convert(time,DATEADD(MILLISECOND,rand()*(@diferenciatiempo+1),'00:00:00')))
insert into Logro(id_insignia,lugar_id,id_usuario,fecha,hora)
values(3,8,77,DATEADD(day,rand()*(@diferenciadias-1+1),@inicio),convert(time,DATEADD(MILLISECOND,rand()*(@diferenciatiempo+1),'00:00:00')))
insert into Logro(id_insignia,lugar_id,id_usuario,fecha,hora)
values(7,15,3,DATEADD(day,rand()*(@diferenciadias-1+1),@inicio),convert(time,DATEADD(MILLISECOND,rand()*(@diferenciatiempo+1),'00:00:00')))
insert into Logro(id_insignia,lugar_id,id_usuario,fecha,hora)
values(1,11,67,DATEADD(day,rand()*(@diferenciadias-1+1),@inicio),convert(time,DATEADD(MILLISECOND,rand()*(@diferenciatiempo+1),'00:00:00')))
insert into Logro(id_insignia,lugar_id,id_usuario,fecha,hora)
values(2,14,72,DATEADD(day,rand()*(@diferenciadias-1+1),@inicio),convert(time,DATEADD(MILLISECOND,rand()*(@diferenciatiempo+1),'00:00:00')))
insert into Logro(id_insignia,lugar_id,id_usuario,fecha,hora)
values(1,1,21,DATEADD(day,rand()*(@diferenciadias-1+1),@inicio),convert(time,DATEADD(MILLISECOND,rand()*(@diferenciatiempo+1),'00:00:00')))
insert into Logro(id_insignia,lugar_id,id_usuario,fecha,hora)
values(2,5,83,DATEADD(day,rand()*(@diferenciadias-1+1),@inicio),convert(time,DATEADD(MILLISECOND,rand()*(@diferenciatiempo+1),'00:00:00')))
insert into Logro(id_insignia,lugar_id,id_usuario,fecha,hora)
values(1,12,107,DATEADD(day,rand()*(@diferenciadias-1+1),@inicio),convert(time,DATEADD(MILLISECOND,rand()*(@diferenciatiempo+1),'00:00:00')))
insert into Logro(id_insignia,lugar_id,id_usuario,fecha,hora)
values(6,2,19,DATEADD(day,rand()*(@diferenciadias-1+1),@inicio),convert(time,DATEADD(MILLISECOND,rand()*(@diferenciatiempo+1),'00:00:00')))
insert into Logro(id_insignia,lugar_id,id_usuario,fecha,hora)
values(1,4,102,DATEADD(day,rand()*(@diferenciadias-1+1),@inicio),convert(time,DATEADD(MILLISECOND,rand()*(@diferenciatiempo+1),'00:00:00')))
insert into Logro(id_insignia,lugar_id,id_usuario,fecha,hora)
values(1,7,13,DATEADD(day,rand()*(@diferenciadias-1+1),@inicio),convert(time,DATEADD(MILLISECOND,rand()*(@diferenciatiempo+1),'00:00:00')))
insert into Logro(id_insignia,lugar_id,id_usuario,fecha,hora)
values(10,5,93,DATEADD(day,rand()*(@diferenciadias-1+1),@inicio),convert(time,DATEADD(MILLISECOND,rand()*(@diferenciatiempo+1),'00:00:00')))
insert into Logro(id_insignia,lugar_id,id_usuario,fecha,hora)
values(3,5,22,DATEADD(day,rand()*(@diferenciadias-1+1),@inicio),convert(time,DATEADD(MILLISECOND,rand()*(@diferenciatiempo+1),'00:00:00')))
insert into Logro(id_insignia,lugar_id,id_usuario,fecha,hora)
values(8,9,18,DATEADD(day,rand()*(@diferenciadias-1+1),@inicio),convert(time,DATEADD(MILLISECOND,rand()*(@diferenciatiempo+1),'00:00:00')))
insert into Logro(id_insignia,lugar_id,id_usuario,fecha,hora)
values(2,14,20,DATEADD(day,rand()*(@diferenciadias-1+1),@inicio),convert(time,DATEADD(MILLISECOND,rand()*(@diferenciatiempo+1),'00:00:00')))
insert into Logro(id_insignia,lugar_id,id_usuario,fecha,hora)
values(9,1,76,DATEADD(day,rand()*(@diferenciadias-1+1),@inicio),convert(time,DATEADD(MILLISECOND,rand()*(@diferenciatiempo+1),'00:00:00')))
insert into Logro(id_insignia,lugar_id,id_usuario,fecha,hora)
values(6,15,5,DATEADD(day,rand()*(@diferenciadias-1+1),@inicio),convert(time,DATEADD(MILLISECOND,rand()*(@diferenciatiempo+1),'00:00:00')))
insert into Logro(id_insignia,lugar_id,id_usuario,fecha,hora)
values(3,11,37,DATEADD(day,rand()*(@diferenciadias-1+1),@inicio),convert(time,DATEADD(MILLISECOND,rand()*(@diferenciatiempo+1),'00:00:00')))
insert into Logro(id_insignia,lugar_id,id_usuario,fecha,hora)
values(9,7,74,DATEADD(day,rand()*(@diferenciadias-1+1),@inicio),convert(time,DATEADD(MILLISECOND,rand()*(@diferenciatiempo+1),'00:00:00')))
insert into Logro(id_insignia,lugar_id,id_usuario,fecha,hora)
values(8,12,89,DATEADD(day,rand()*(@diferenciadias-1+1),@inicio),convert(time,DATEADD(MILLISECOND,rand()*(@diferenciatiempo+1),'00:00:00')))
insert into Logro(id_insignia,lugar_id,id_usuario,fecha,hora)
values(1,1,25,DATEADD(day,rand()*(@diferenciadias-1+1),@inicio),convert(time,DATEADD(MILLISECOND,rand()*(@diferenciatiempo+1),'00:00:00')))
insert into Logro(id_insignia,lugar_id,id_usuario,fecha,hora)
values(7,13,35,DATEADD(day,rand()*(@diferenciadias-1+1),@inicio),convert(time,DATEADD(MILLISECOND,rand()*(@diferenciatiempo+1),'00:00:00')))
insert into Logro(id_insignia,lugar_id,id_usuario,fecha,hora)
values(9,6,54,DATEADD(day,rand()*(@diferenciadias-1+1),@inicio),convert(time,DATEADD(MILLISECOND,rand()*(@diferenciatiempo+1),'00:00:00')))
insert into Logro(id_insignia,lugar_id,id_usuario,fecha,hora)
values(6,15,93,DATEADD(day,rand()*(@diferenciadias-1+1),@inicio),convert(time,DATEADD(MILLISECOND,rand()*(@diferenciatiempo+1),'00:00:00')))
insert into Logro(id_insignia,lugar_id,id_usuario,fecha,hora)
values(8,1,64,DATEADD(day,rand()*(@diferenciadias-1+1),@inicio),convert(time,DATEADD(MILLISECOND,rand()*(@diferenciatiempo+1),'00:00:00')))
insert into Logro(id_insignia,lugar_id,id_usuario,fecha,hora)
values(6,4,60,DATEADD(day,rand()*(@diferenciadias-1+1),@inicio),convert(time,DATEADD(MILLISECOND,rand()*(@diferenciatiempo+1),'00:00:00')))
insert into Logro(id_insignia,lugar_id,id_usuario,fecha,hora)
values(5,15,39,DATEADD(day,rand()*(@diferenciadias-1+1),@inicio),convert(time,DATEADD(MILLISECOND,rand()*(@diferenciatiempo+1),'00:00:00')))
insert into Logro(id_insignia,lugar_id,id_usuario,fecha,hora)
values(7,10,4,DATEADD(day,rand()*(@diferenciadias-1+1),@inicio),convert(time,DATEADD(MILLISECOND,rand()*(@diferenciatiempo+1),'00:00:00')))
insert into Logro(id_insignia,lugar_id,id_usuario,fecha,hora)
values(8,13,74,DATEADD(day,rand()*(@diferenciadias-1+1),@inicio),convert(time,DATEADD(MILLISECOND,rand()*(@diferenciatiempo+1),'00:00:00')))

