Use [Gallo Giro]
Go
---6to Paso: Cargas iniciales
select*from Ciudad
insert into Ciudad(Nombre)
values('Anáhuac'), ('CD. Obregón'),('Chihuahua'),('Culiacan'), ('Guamuchil'),('Guaymas'), ('Hermosillo'),('Mazatlán'),('CD.Cuauthemoc'),('Navojoa')

---Colonia
select * from Colonia
INSERT INTO Colonia(Nombre,ID_Ciudad)
VALUES('Barranchos',4)
insert into Colonia (Nombre,ID_Ciudad)
values('Lomas del Sol',4)
insert into Colonia(Nombre,ID_Ciudad)
values('Las Quintas',4)
insert into Colonia (Nombre,ID_Ciudad)
values('Los venados',8)
insert into Colonia (Nombre,ID_Ciudad)
values('El Conchi',8)
insert into Colonia (Nombre,ID_Ciudad)
values('Cerro Gandereño',6)
insert into Colonia (Nombre,ID_Ciudad)
values('Las Plazas',6)
insert into Colonia (Nombre,ID_Ciudad)
values('Petrolera',6)
insert into Colonia (Nombre,ID_Ciudad)
values('La Matanza',7)
insert into Colonia (Nombre,ID_Ciudad)
values('Parque Industrial',7)
insert into Colonia (Nombre,ID_Ciudad)
values('Obrera',3)
insert into Colonia (Nombre,ID_Ciudad)
values('El Pedregal',1)
insert into Colonia (Nombre,ID_Ciudad)
values('Real de Sevilla',2)
insert into Colonia (Nombre,ID_Ciudad)
values('Satelite',2)
insert into Colonia (Nombre,ID_Ciudad)
values('Progreso',9)
insert into Colonia (Nombre,ID_Ciudad)
values('Francisco Villa',9)
insert into Colonia (Nombre,ID_Ciudad)
values('Morelos',5)
insert into Colonia (Nombre,ID_Ciudad)
values('Sonora Progresista',10)


---Calle
select Calle.Nombre,Calle.ID,Ciudad.Nombre from Calle inner join Ciudad on Ciudad.ID=Calle.ID_Ciudad order by Calle.ID
select Colonia.ID,Colonia.Nombre,Ciudad.Nombre from Colonia inner join Ciudad on Ciudad.ID=Colonia.ID_Ciudad order by Colonia.ID
insert into Calle(Nombre,ID_Ciudad)
values('Av. Gral. Maximiliano Gamez',4)
insert into Calle(Nombre,ID_Ciudad)
values('Profa. Emiliano Zapata',4)
insert into Calle(Nombre,ID_Ciudad)
values('Gral. Angel Flores',4)
insert into Calle(Nombre,ID_Ciudad)
values('Vison',8)
insert into Calle(Nombre,ID_Ciudad)
values('La Amapá',8)
insert into Calle(Nombre,ID_Ciudad)
values('Manuel J. Clouthier',8)
insert into Calle(Nombre,ID_Ciudad)
values('Calle Ocho',6)
insert into Calle(Nombre,ID_Ciudad)
values('Plaza del Centenario',6)
insert into Calle(Nombre,ID_Ciudad)
values('Oscar Ruiz Almeida',6)
insert into Calle(Nombre,ID_Ciudad)
values('5 de febrero',1)
insert into Calle(Nombre,ID_Ciudad)
values('Nicaragua',7)
insert into Calle(Nombre,ID_Ciudad)
values('Calle Ignacio Zaragoza',2)
insert into Calle(Nombre,ID_Ciudad)
values('Sta Matilde',2)
insert into Calle(Nombre,ID_Ciudad)
values('San Clemente',2)
insert into Calle(Nombre,ID_Ciudad)
values('21 de marzo',9)
insert into Calle(Nombre,ID_Ciudad)
values('10 de mayo',9)
insert into Calle(Nombre,ID_Ciudad)
values('Calle Mina',7)
insert into Calle(Nombre,ID_Ciudad)
values('De los pimas',7)
insert into Calle(Nombre,ID_Ciudad)
values('Mariano Jiménez',9)
insert into Calle(Nombre,ID_Ciudad)
values('Leona Vicario',9)
insert into Calle(Nombre,ID_Ciudad)
values('Marcelo Cubillas',10)
insert into Calle(Nombre,ID_Ciudad)
values('16 de septiembre',5)
insert into Calle(Nombre,ID_Ciudad)
values('José Maria Morelos',5)
insert into Calle(Nombre,ID_Ciudad)
values('Calle 35',3)
insert into Calle(Nombre,ID_Ciudad)
values('Mariano Horcasitas',3)
insert into Calle(Nombre,ID_Ciudad)
values('Felipe Bárcenas Sartini',6)
insert into Calle(Nombre,ID_Ciudad)
values('Lago de Patzcuaro',4)
insert into Calle(Nombre,ID_Ciudad)
values('Laguna',1)
insert into Calle(Nombre,ID_Ciudad)
values('Jesus García',10)
insert into Calle(Nombre,ID_Ciudad)
values('De los deportes',1)
insert into Calle(Nombre,ID_Ciudad)
values('Calz de las Americas',4)

---Dirección
select*from Dirección order by ID
insert into Dirección(CP,Número,ID_Calle,ID_Colonia)
values(80190,3190,1,1)
insert into Dirección(CP,Número,ID_Calle,ID_Colonia)
values(80016,2145,2,2)
insert into Dirección(CP,Número,ID_Calle,ID_Colonia)
values(80060,1112,3,3)
insert into Dirección(CP,Número,ID_Calle,ID_Colonia)
values(82154,84,4,4)
insert into Dirección(CP,Número,ID_Calle,ID_Colonia)
values(82190,313,5,5)
insert into Dirección(CP,Número,ID_Calle,ID_Colonia)
values(82190,null,6,5)
insert into Dirección(CP,Número,ID_Calle,ID_Colonia)
values(85440,124,7,6)
insert into Dirección(CP,Número,ID_Calle,ID_Colonia)
values(85440,13,8,7)
insert into Dirección(CP,Número,ID_Calle,ID_Colonia)
values(85456,205,9,8)
insert into Dirección(CP,Número,ID_Calle,ID_Colonia)
values(31600,202,10,12)
insert into Dirección(CP,Número,ID_Calle,ID_Colonia)
values(85060,null,12,14)
insert into Dirección(CP,Número,ID_Calle,ID_Colonia)
values(null,517,13,13)
insert into Dirección(CP,Número,ID_Calle,ID_Colonia)
values(,,,)

---Almacen
select*from Almacen
insert into Almacen(ID_Dirección)
values(6),(2),(3),(1),(4),(5),(8)

---Tipo Clientes
select*from TipoCliente
insert into TipoCliente(ID,Tipo,Descripción)
values(1,'Domestico','Personas que compran productos para su jardín o huerto familiar.'),
(2,'Agricultor','Persona que siembra grandes cantidades de tierra.')

---Cliente
--select*from [Cliente]
--insert into [Cliente]()